/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/authenticate/baseauth": {
        /** Returns returns an API key for authenticated user based on BaseAuth headers. */
        get: operations["authenticate__baseauth"]
    }
    "/api/categories": {
        /**
         * Index
         * @description index category
         */
        get: operations["categories__index"]
        /**
         * Create
         * @description create a category
         */
        post: operations["categories__create"]
    }
    "/api/categories/{encoded_category_id}": {
        /**
         * Show
         * @description show category
         */
        get: operations["categories__show"]
    }
    "/api/categories/{encoded_category_id}/repositories": {
        /**
         * Repositories
         * @description display repositories by category
         */
        get: operations["categories__repositories"]
    }
    "/api/ga4gh/trs/v2/service-info": {
        /** Service Info */
        get: operations["tools_trs_service_info"]
    }
    "/api/ga4gh/trs/v2/toolClasses": {
        /** Tool Classes */
        get: operations["tools__trs_tool_classes"]
    }
    "/api/ga4gh/trs/v2/tools": {
        /** Trs Index */
        get: operations["tools__trs_index"]
    }
    "/api/ga4gh/trs/v2/tools/{tool_id}": {
        /** Trs Get */
        get: operations["tools__trs_get"]
    }
    "/api/ga4gh/trs/v2/tools/{tool_id}/versions": {
        /** Trs Get Versions */
        get: operations["tools__trs_get_versions"]
    }
    "/api/repositories": {
        /**
         * Index
         * @description Get a list of repositories or perform a search.
         */
        get: operations["repositories__index"]
        /**
         * Create
         * @description create a new repository
         */
        post: operations["repositories__create"]
    }
    "/api/repositories/get_ordered_installable_revisions": {
        /**
         * Get Ordered Installable Revisions
         * @description Get an ordered list of the repository changeset revisions that are installable
         */
        get: operations["repositories__get_ordered_installable_revisions"]
    }
    "/api/repositories/get_repository_revision_install_info": {
        /**
         * Legacy Install Info
         * @description Get information used by the install client to install this repository.
         */
        get: operations["repositories__legacy_install_info"]
    }
    "/api/repositories/install_info": {
        /**
         * Install Info
         * @description Get information used by the install client to install this repository.
         */
        get: operations["repositories__install_info"]
    }
    "/api/repositories/reset_metadata_on_repository": {
        /**
         * Reset Metadata On Repository Legacy
         * @description reset metadata on a repository
         */
        post: operations["repositories__reset_legacy"]
    }
    "/api/repositories/updates": {
        /** Updates */
        get: operations["repositories__update"]
    }
    "/api/repositories/{encoded_repository_id}": {
        /** Show */
        get: operations["repositories__show"]
    }
    "/api/repositories/{encoded_repository_id}/allow_push": {
        /** Show Allow Push */
        get: operations["repositories__show_allow_push"]
    }
    "/api/repositories/{encoded_repository_id}/allow_push/{username}": {
        /** Add Allow Push */
        post: operations["repositories__add_allow_push"]
        /** Remove Allow Push */
        delete: operations["repositories__remove_allow_push"]
    }
    "/api/repositories/{encoded_repository_id}/changeset_revision": {
        /**
         * Create Changeset Revision
         * @description upload new revision to the repository
         */
        post: operations["repositories__create_revision"]
    }
    "/api/repositories/{encoded_repository_id}/deprecated": {
        /** Set Deprecated */
        put: operations["repositories__set_deprecated"]
        /** Unset Deprecated */
        delete: operations["repositories__unset_deprecated"]
    }
    "/api/repositories/{encoded_repository_id}/metadata": {
        /**
         * Metadata
         * @description Get information about repository metadata
         */
        get: operations["repositories__metadata"]
    }
    "/api/repositories/{encoded_repository_id}/permissions": {
        /** Permissions */
        get: operations["repositories__permissions"]
    }
    "/api/repositories/{encoded_repository_id}/reset_metadata": {
        /**
         * Reset Metadata On Repository
         * @description reset metadata on a repository
         */
        post: operations["repositories__reset"]
    }
    "/api/repositories/{encoded_repository_id}/revisions/{changeset_revision}/malicious": {
        /** Set Malicious */
        put: operations["repositories__set_malicious"]
        /** Unset Malicious */
        delete: operations["repositories__unset_malicious"]
    }
    "/api/repositories/{encoded_repository_id}/revisions/{changeset_revision}/readmes": {
        /**
         * Get Readmes
         * @description fetch readmes for repository revision
         */
        get: operations["repositories__readmes"]
    }
    "/api/tools": {
        /** Index */
        get: operations["tools__index"]
    }
    "/api/tools/build_search_index": {
        /**
         * Build Search Index
         * @description Not part of the stable API, just something to simplify
         * bootstrapping tool sheds, scripting, testing, etc...
         */
        put: operations["tools__build_search_index"]
    }
    "/api/users": {
        /**
         * Index
         * @description index users
         */
        get: operations["users__index"]
        /**
         * Create
         * @description create a user
         */
        post: operations["users__create"]
    }
    "/api/users/current": {
        /**
         * Current
         * @description show current user
         */
        get: operations["users__current"]
    }
    "/api/users/{encoded_user_id}": {
        /**
         * Show
         * @description show a user
         */
        get: operations["users__show"]
    }
    "/api/users/{encoded_user_id}/api_key": {
        /** Return the user's API key */
        get: operations["users__get_or_create_api_key"]
        /** Creates a new API key for the user */
        post: operations["users__create_api_key"]
        /** Delete the current API key of the user */
        delete: operations["users__delete_api_key"]
    }
    "/api/version": {
        /** Version */
        get: operations["configuration__version"]
    }
    "/api_internal/change_password": {
        /**
         * Change Password
         * @description reset a user
         */
        put: operations["users__internal_change_password"]
    }
    "/api_internal/login": {
        /**
         * Internal Login
         * @description login to web UI
         */
        put: operations["users__internal_login"]
    }
    "/api_internal/logout": {
        /**
         * Internal Logout
         * @description logout of web UI
         */
        put: operations["users__internal_logout"]
    }
    "/api_internal/register": {
        /**
         * Register
         * @description register a user
         */
        post: operations["users__internal_register"]
    }
    "/api_internal/repositories/{encoded_repository_id}/metadata": {
        /**
         * Metadata Internal
         * @description Get information about repository metadata
         */
        get: operations["repositories__internal_metadata"]
    }
}

export type webhooks = Record<string, never>

export interface components {
    schemas: {
        /** APIKeyResponse */
        APIKeyResponse: {
            /** Api Key */
            api_key: string
        }
        /** Body_repositories__create_revision */
        Body_repositories__create_revision: {
            /** Commit Message */
            commit_message?: Record<string, never>
            /** Files */
            files?: string[]
        }
        /** BuildSearchIndexResponse */
        BuildSearchIndexResponse: {
            /** Repositories Indexed */
            repositories_indexed: number
            /** Tools Indexed */
            tools_indexed: number
        }
        /** Category */
        Category: {
            /** Deleted */
            deleted: boolean
            /** Description */
            description: string
            /** Id */
            id: string
            /** Name */
            name: string
            /** Repositories */
            repositories: number
        }
        /** Checksum */
        Checksum: {
            /**
             * Checksum
             * @description The hex-string encoded checksum for the data.
             */
            checksum: string
            /**
             * Type
             * @description The digest method used to create the checksum.
             * The value (e.g. `sha-256`) SHOULD be listed as `Hash Name String` in the https://github.com/ga4gh-discovery/ga4gh-checksum/blob/master/hash-alg.csv[GA4GH Checksum Hash Algorithm Registry].
             * Other values MAY be used, as long as implementors are aware of the issues discussed in https://tools.ietf.org/html/rfc6920#section-9.4[RFC6920].
             * GA4GH may provide more explicit guidance for use of non-IANA-registered algorithms in the future.
             */
            type: string
        }
        /** CreateCategoryRequest */
        CreateCategoryRequest: {
            /** Description */
            description?: string
            /** Name */
            name: string
        }
        /** CreateRepositoryRequest */
        CreateRepositoryRequest: {
            /** Category IDs */
            "category_ids[]": string
            /** Description */
            description?: string
            /** Homepage Url */
            homepage_url?: string
            /** Name */
            name: string
            /** Remote Repository Url */
            remote_repository_url?: string
            /** Synopsis */
            synopsis: string
            /**
             * Type
             * @default unrestricted
             * @enum {string}
             */
            type?: "repository_suite_definition" | "tool_dependency_definition" | "unrestricted"
        }
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Email */
            email: string
            /** Password */
            password: string
            /** Username */
            username: string
        }
        /**
         * DescriptorType
         * @description An enumeration.
         * @enum {unknown}
         */
        DescriptorType: "CWL" | "WDL" | "NFL" | "GALAXY" | "SMK"
        /**
         * DescriptorTypeVersion
         * @description The language version for a given descriptor type. The version should correspond to the actual declared version of the descriptor. For example, tools defined in CWL could have a version of `v1.0.2` whereas WDL tools may have a version of `1.0` or `draft-2`
         */
        DescriptorTypeVersion: string
        /** DetailedRepository */
        DetailedRepository: {
            /** Create Time */
            create_time: string
            /** Deleted */
            deleted: boolean
            /** Deprecated */
            deprecated: boolean
            /** Description */
            description: string
            /** Homepage Url */
            homepage_url?: string
            /** Id */
            id: string
            /** Long Description */
            long_description?: string
            /** Name */
            name: string
            /** Owner */
            owner: string
            /** Private */
            private: boolean
            /** Remote Repository Url */
            remote_repository_url?: string
            /** Times Downloaded */
            times_downloaded: number
            /** Type */
            type: string
            /** Update Time */
            update_time: string
            /** User Id */
            user_id: string
        }
        /** FailedRepositoryUpdateMessage */
        FailedRepositoryUpdateMessage: {
            /** Err Msg */
            err_msg: string
        }
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][]
        }
        /** ImageData */
        ImageData: {
            /**
             * Checksum
             * @description A production (immutable) tool version is required to have a hashcode. Not required otherwise, but might be useful to detect changes.  This exposes the hashcode for specific image versions to verify that the container version pulled is actually the version that was indexed by the registry.
             * @example [
             *   {
             *     "checksum": "77af4d6b9913e693e8d0b4b294fa62ade6054e6b2f1ffb617ac955dd63fb0182",
             *     "type": "sha256"
             *   }
             * ]
             */
            checksum?: components["schemas"]["Checksum"][]
            /**
             * Image Name
             * @description Used in conjunction with a registry_url if provided to locate images.
             * @example [
             *   "quay.io/seqware/seqware_full/1.1",
             *   "ubuntu:latest"
             * ]
             */
            image_name?: string
            image_type?: components["schemas"]["ImageType"]
            /**
             * Registry Host
             * @description A docker registry or a URL to a Singularity registry. Used along with image_name to locate a specific image.
             * @example [
             *   "registry.hub.docker.com"
             * ]
             */
            registry_host?: string
            /**
             * Size
             * @description Size of the container in bytes.
             */
            size?: number
            /**
             * Updated
             * @description Last time the container was updated.
             */
            updated?: string
        }
        /**
         * ImageType
         * @description An enumeration.
         * @enum {unknown}
         */
        ImageType: "Docker" | "Singularity" | "Conda"
        /** InstallInfo */
        InstallInfo: {
            metadata_info?: components["schemas"]["RepositoryMetadataInstallInfo"]
            repo_info?: components["schemas"]["RepositoryExtraInstallInfo"]
        }
        /** Organization */
        Organization: {
            /**
             * Name
             * @description Name of the organization responsible for the service
             * @example My organization
             */
            name: string
            /**
             * Url
             * Format: uri
             * @description URL of the website of the organization (RFC 3986 format)
             * @example https://example.com
             */
            url: string
        }
        /** RepositoriesByCategory */
        RepositoriesByCategory: {
            /** Description */
            description: string
            /** Id */
            id: string
            /** Name */
            name: string
            /** Repositories */
            repositories: components["schemas"]["Repository"][]
            /** Repository Count */
            repository_count: number
        }
        /** Repository */
        Repository: {
            /** Create Time */
            create_time: string
            /** Deleted */
            deleted: boolean
            /** Deprecated */
            deprecated: boolean
            /** Description */
            description: string
            /** Homepage Url */
            homepage_url?: string
            /** Id */
            id: string
            /** Name */
            name: string
            /** Owner */
            owner: string
            /** Private */
            private: boolean
            /** Remote Repository Url */
            remote_repository_url?: string
            /** Times Downloaded */
            times_downloaded: number
            /** Type */
            type: string
            /** Update Time */
            update_time: string
            /** User Id */
            user_id: string
        }
        /** RepositoryDependency */
        RepositoryDependency: {
            /** Changeset Revision */
            changeset_revision: string
            /** Downloadable */
            downloadable: boolean
            /** Has Repository Dependencies */
            has_repository_dependencies: boolean
            /** Id */
            id: string
            /** Includes Datatypes */
            includes_datatypes?: boolean
            /** Includes Tool Dependencies */
            includes_tool_dependencies?: boolean
            /** Includes Tools */
            includes_tools: boolean
            /** Includes Tools For Display In Tool Panel */
            includes_tools_for_display_in_tool_panel: boolean
            /** Includes Workflows */
            includes_workflows?: boolean
            /** Invalid Tools */
            invalid_tools: string[]
            /** Malicious */
            malicious: boolean
            /** Missing Test Components */
            missing_test_components: boolean
            /** Numeric Revision */
            numeric_revision: number
            repository: components["schemas"]["Repository"]
            /** Repository Dependencies */
            repository_dependencies: components["schemas"]["RepositoryDependency"][]
            /** Repository Id */
            repository_id: string
            /** Tools */
            tools?: components["schemas"]["RepositoryTool"][]
        }
        /** RepositoryExtraInstallInfo */
        RepositoryExtraInstallInfo: {
            /** Changeset Revision */
            changeset_revision: string
            /** Ctx Rev */
            ctx_rev: string
            /** Description */
            description: string
            /** Name */
            name: string
            /** Repository Clone Url */
            repository_clone_url: string
            /** Repository Dependencies */
            repository_dependencies?: Record<string, never>
            /** Repository Owner */
            repository_owner: string
        }
        /** RepositoryMetadata */
        RepositoryMetadata: {
            [key: string]: components["schemas"]["RepositoryRevisionMetadata"] | undefined
        }
        /** RepositoryMetadataInstallInfo */
        RepositoryMetadataInstallInfo: {
            /** Changeset Revision */
            changeset_revision: string
            /** Downloadable */
            downloadable: boolean
            /** Has Repository Dependencies */
            has_repository_dependencies: boolean
            /** Id */
            id: string
            /** Includes Tools */
            includes_tools: boolean
            /** Includes Tools For Display In Tool Panel */
            includes_tools_for_display_in_tool_panel: boolean
            /** Malicious */
            malicious: boolean
            /** Repository Id */
            repository_id: string
            /** Url */
            url: string
            /** Valid Tools */
            valid_tools: components["schemas"]["ValidToolDict"][]
        }
        /** RepositoryPermissions */
        RepositoryPermissions: {
            /** Allow Push */
            allow_push: string[]
            /** Can Manage */
            can_manage: boolean
            /** Can Push */
            can_push: boolean
        }
        /** RepositoryRevisionMetadata */
        RepositoryRevisionMetadata: {
            /** Changeset Revision */
            changeset_revision: string
            /** Downloadable */
            downloadable: boolean
            /** Has Repository Dependencies */
            has_repository_dependencies: boolean
            /** Id */
            id: string
            /** Includes Datatypes */
            includes_datatypes?: boolean
            /** Includes Tool Dependencies */
            includes_tool_dependencies?: boolean
            /** Includes Tools */
            includes_tools: boolean
            /** Includes Tools For Display In Tool Panel */
            includes_tools_for_display_in_tool_panel: boolean
            /** Includes Workflows */
            includes_workflows?: boolean
            /** Invalid Tools */
            invalid_tools: string[]
            /** Malicious */
            malicious: boolean
            /** Missing Test Components */
            missing_test_components: boolean
            /** Numeric Revision */
            numeric_revision: number
            repository: components["schemas"]["Repository"]
            /** Repository Dependencies */
            repository_dependencies: components["schemas"]["RepositoryDependency"][]
            /** Repository Id */
            repository_id: string
            /** Tools */
            tools?: components["schemas"]["RepositoryTool"][]
        }
        /** RepositoryRevisionReadmes */
        RepositoryRevisionReadmes: {
            [key: string]: string | undefined
        }
        /** RepositorySearchHit */
        RepositorySearchHit: {
            repository: components["schemas"]["RepositorySearchResult"]
            /** Score */
            score: number
        }
        /** RepositorySearchResult */
        RepositorySearchResult: {
            /** Approved */
            approved: boolean
            /** Categories */
            categories: string
            /** Description */
            description: string
            /** Full Last Updated */
            full_last_updated: string
            /** Homepage Url */
            homepage_url?: string
            /** Id */
            id: string
            /** Last Update */
            last_update?: string
            /** Long Description */
            long_description?: string
            /** Name */
            name: string
            /** Remote Repository Url */
            remote_repository_url?: string
            /** Repo Lineage */
            repo_lineage: string
            /** Repo Owner Username */
            repo_owner_username: string
            /** Times Downloaded */
            times_downloaded: number
        }
        /** RepositorySearchResults */
        RepositorySearchResults: {
            /** Hits */
            hits: components["schemas"]["RepositorySearchHit"][]
            /** Hostname */
            hostname: string
            /** Page */
            page: string
            /** Page Size */
            page_size: string
            /** Total Results */
            total_results: string
        }
        /** RepositoryTool */
        RepositoryTool: {
            /** Description */
            description: string
            /** Guid */
            guid: string
            /** Id */
            id: string
            /** Name */
            name: string
            /** Requirements */
            requirements: Record<string, never>[]
            /** Tool Config */
            tool_config: string
            /** Tool Type */
            tool_type: string
            /** Version */
            version: string
        }
        /** RepositoryUpdate */
        RepositoryUpdate:
            | components["schemas"]["ValidRepostiroyUpdateMessage"]
            | components["schemas"]["FailedRepositoryUpdateMessage"]
        /** ResetMetadataOnRepositoryResponse */
        ResetMetadataOnRepositoryResponse: {
            /** Repository Status */
            repository_status: string[]
            /** Start Time */
            start_time: string
            /** Status */
            status: string
            /** Stop Time */
            stop_time: string
        }
        /** Service */
        Service: {
            /**
             * Contacturl
             * Format: uri
             * @description URL of the contact for the provider of this service, e.g. a link to a contact form (RFC 3986 format), or an email (RFC 2368 format).
             * @example mailto:support@example.com
             */
            contactUrl?: string
            /**
             * Createdat
             * Format: date-time
             * @description Timestamp describing when the service was first deployed and available (RFC 3339 format)
             * @example 2019-06-04T12:58:19Z
             */
            createdAt?: string
            /**
             * Description
             * @description Description of the service. Should be human readable and provide information about the service.
             * @example This service provides...
             */
            description?: string
            /**
             * Documentationurl
             * Format: uri
             * @description URL of the documentation of this service (RFC 3986 format). This should help someone learn how to use your service, including any specifics required to access data, e.g. authentication.
             * @example https://docs.myservice.example.com
             */
            documentationUrl?: string
            /**
             * Environment
             * @description Environment the service is running in. Use this to distinguish between production, development and testing/staging deployments. Suggested values are prod, test, dev, staging. However this is advised and not enforced.
             * @example test
             */
            environment?: string
            /**
             * Id
             * @description Unique ID of this service. Reverse domain name notation is recommended, though not required. The identifier should attempt to be globally unique so it can be used in downstream aggregator services e.g. Service Registry.
             * @example org.ga4gh.myservice
             */
            id: string
            /**
             * Name
             * @description Name of this service. Should be human readable.
             * @example My project
             */
            name: string
            /**
             * Organization
             * @description Organization providing the service
             */
            organization: components["schemas"]["Organization"]
            type: components["schemas"]["ServiceType"]
            /**
             * Updatedat
             * Format: date-time
             * @description Timestamp describing when the service was last updated (RFC 3339 format)
             * @example 2019-06-04T12:58:19Z
             */
            updatedAt?: string
            /**
             * Version
             * @description Version of the service being described. Semantic versioning is recommended, but other identifiers, such as dates or commit hashes, are also allowed. The version should be changed whenever the service is updated.
             * @example 1.0.0
             */
            version: string
        }
        /** ServiceType */
        ServiceType: {
            /**
             * Artifact
             * @description Name of the API or GA4GH specification implemented. Official GA4GH types should be assigned as part of standards approval process. Custom artifacts are supported.
             * @example beacon
             */
            artifact: string
            /**
             * Group
             * @description Namespace in reverse domain name format. Use `org.ga4gh` for implementations compliant with official GA4GH specifications. For services with custom APIs not standardized by GA4GH, or implementations diverging from official GA4GH specifications, use a different namespace (e.g. your organization's reverse domain name).
             * @example org.ga4gh
             */
            group: string
            /**
             * Version
             * @description Version of the API or specification. GA4GH specifications use semantic versioning.
             * @example 1.0.0
             */
            version: string
        }
        /** Tool */
        Tool: {
            /**
             * Aliases
             * @description Support for this parameter is optional for tool registries that support aliases.
             * A list of strings that can be used to identify this tool which could be  straight up URLs.
             * This can be used to expose alternative ids (such as GUIDs) for a tool
             * for registries. Can be used to match tools across registries.
             */
            aliases?: string[]
            /**
             * Checker Url
             * @description Optional url to the checker tool that will exit successfully if this tool produced the expected result given test data.
             */
            checker_url?: string
            /**
             * Description
             * @description The description of the tool.
             */
            description?: string
            /**
             * Has Checker
             * @description Whether this tool has a checker tool associated with it.
             */
            has_checker?: boolean
            /**
             * Id
             * @description A unique identifier of the tool, scoped to this registry.
             * @example 123456
             */
            id: string
            /**
             * Meta Version
             * @description The version of this tool in the registry. Iterates when fields like the description, author, etc. are updated.
             */
            meta_version?: string
            /**
             * Name
             * @description The name of the tool.
             */
            name?: string
            /**
             * Organization
             * @description The organization that published the image.
             */
            organization: string
            toolclass: components["schemas"]["ToolClass"]
            /**
             * Url
             * @description The URL for this tool in this registry.
             * @example http://agora.broadinstitute.org/tools/123456
             */
            url: string
            /**
             * Versions
             * @description A list of versions for this tool.
             */
            versions: components["schemas"]["ToolVersion"][]
        }
        /** ToolClass */
        ToolClass: {
            /**
             * Description
             * @description A longer explanation of what this class is and what it can accomplish.
             */
            description?: string
            /**
             * Id
             * @description The unique identifier for the class.
             */
            id?: string
            /**
             * Name
             * @description A short friendly name for the class.
             */
            name?: string
        }
        /** ToolVersion */
        ToolVersion: {
            /**
             * Author
             * @description Contact information for the author of this version of the tool in the registry. (More complex authorship information is handled by the descriptor).
             */
            author?: string[]
            /**
             * Containerfile
             * @description Reports if this tool has a containerfile available. (For Docker-based tools, this would indicate the presence of a Dockerfile)
             */
            containerfile?: boolean
            /** @description The type (or types) of descriptors available. */
            descriptor_type?: components["schemas"]["DescriptorType"][]
            /**
             * Descriptor Type Version
             * @description A map providing information about the language versions used in this tool. The keys should be the same values used in the `descriptor_type` field, and the value should be an array of all the language versions used for the given `descriptor_type`. Depending on the `descriptor_type` (e.g. CWL) multiple version values may be used in a single tool.
             * @example {
             *   "WDL": ["1.0", "1.0"],
             *   "CWL": ["v1.0.2"],
             *   "NFL": ["DSL2"]
             * }
             */
            descriptor_type_version?: {
                [key: string]: components["schemas"]["DescriptorTypeVersion"][] | undefined
            }
            /**
             * Id
             * @description An identifier of the version of this tool for this particular tool registry.
             * @example v1
             */
            id: string
            /**
             * Images
             * @description All known docker images (and versions/hashes) used by this tool. If the tool has to evaluate any of the docker images strings at runtime, those ones cannot be reported here.
             */
            images?: components["schemas"]["ImageData"][]
            /**
             * Included Apps
             * @description An array of IDs for the applications that are stored inside this tool.
             * @example [
             *   "https://bio.tools/tool/mytum.de/SNAP2/1",
             *   "https://bio.tools/bioexcel_seqqc"
             * ]
             */
            included_apps?: string[]
            /**
             * Is Production
             * @description This version of a tool is guaranteed to not change over time (for example, a  tool built from a tag in git as opposed to a branch). A production quality tool  is required to have a checksum
             */
            is_production?: boolean
            /**
             * Meta Version
             * @description The version of this tool version in the registry. Iterates when fields like the description, author, etc. are updated.
             */
            meta_version?: string
            /**
             * Name
             * @description The name of the version.
             */
            name?: string
            /**
             * Signed
             * @description Reports whether this version of the tool has been signed.
             */
            signed?: boolean
            /**
             * Url
             * @description The URL for this tool version in this registry.
             * @example http://agora.broadinstitute.org/tools/123456/versions/1
             */
            url: string
            /**
             * Verified
             * @description Reports whether this tool has been verified by a specific organization or individual.
             */
            verified?: boolean
            /**
             * Verified Source
             * @description Source of metadata that can support a verified tool, such as an email or URL.
             */
            verified_source?: string[]
        }
        /** UiChangePasswordRequest */
        UiChangePasswordRequest: {
            /** Current */
            current: string
            /** Password */
            password: string
        }
        /** UiLoginRequest */
        UiLoginRequest: {
            /** Login */
            login: string
            /** Password */
            password: string
            /** Session Csrf Token */
            session_csrf_token: string
        }
        /** UiLoginResponse */
        UiLoginResponse: Record<string, never>
        /** UiLogoutRequest */
        UiLogoutRequest: {
            /**
             * Logout All
             * @default false
             */
            logout_all?: boolean
            /** Session Csrf Token */
            session_csrf_token: string
        }
        /** UiLogoutResponse */
        UiLogoutResponse: Record<string, never>
        /** UiRegisterRequest */
        UiRegisterRequest: {
            /** Bear Field */
            bear_field: string
            /** Email */
            email: string
            /** Password */
            password: string
            /** Username */
            username: string
        }
        /** UiRegisterResponse */
        UiRegisterResponse: {
            /**
             * Activation Error
             * @default false
             */
            activation_error?: boolean
            /**
             * Activation Sent
             * @default false
             */
            activation_sent?: boolean
            /** Contact Email */
            contact_email?: string
            /** Email */
            email: string
        }
        /** UserV2 */
        UserV2: {
            /** Id */
            id: string
            /** Is Admin */
            is_admin: boolean
            /** Username */
            username: string
        }
        /** ValidRepostiroyUpdateMessage */
        ValidRepostiroyUpdateMessage: {
            /** Message */
            message: string
        }
        /** ValidToolDict */
        ValidToolDict: {
            /** Add To Tool Panel */
            add_to_tool_panel: boolean
            /** Description */
            description: string
            /** Guid */
            guid: string
            /** Id */
            id: string
            /** Name */
            name: string
            /** Requirements */
            requirements: Record<string, never>[]
            /** Tests */
            tests: Record<string, never>[]
            /** Tool Config */
            tool_config: string
            /** Tool Type */
            tool_type: string
            /** Version */
            version: string
            /** Version String Cmd */
            version_string_cmd: string
        }
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: string[]
            /** Message */
            msg: string
            /** Error Type */
            type: string
        }
        /** Version */
        Version: {
            /**
             * Api Version
             * @default v1
             */
            api_version?: string
            /** Version */
            version: string
            /** Version Major */
            version_major: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}

export type external = Record<string, never>

export interface operations {
    authenticate__baseauth: {
        /** Returns returns an API key for authenticated user based on BaseAuth headers. */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["APIKeyResponse"]
                }
            }
        }
    }
    categories__index: {
        /**
         * Index
         * @description index category
         */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["Category"][]
                }
            }
        }
    }
    categories__create: {
        /**
         * Create
         * @description create a category
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["Category"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    categories__show: {
        /**
         * Show
         * @description show category
         */
        parameters: {
            /** @description The encoded database identifier of the category. */
            path: {
                encoded_category_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["Category"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    categories__repositories: {
        /**
         * Repositories
         * @description display repositories by category
         */
        parameters: {
            query?: {
                installable?: boolean
                sort_key?: string
                sort_order?: string
                page?: number
            }
            /** @description The encoded database identifier of the category. */
            path: {
                encoded_category_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["RepositoriesByCategory"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    tools_trs_service_info: {
        /** Service Info */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["Service"]
                }
            }
        }
    }
    tools__trs_tool_classes: {
        /** Tool Classes */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["ToolClass"][]
                }
            }
        }
    }
    tools__trs_index: {
        /** Trs Index */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": Record<string, never>
                }
            }
        }
    }
    tools__trs_get: {
        /** Trs Get */
        parameters: {
            /** @description See also https://ga4gh.github.io/tool-registry-service-schemas/DataModel/#trs-tool-and-trs-tool-version-ids */
            path: {
                tool_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["Tool"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    tools__trs_get_versions: {
        /** Trs Get Versions */
        parameters: {
            /** @description See also https://ga4gh.github.io/tool-registry-service-schemas/DataModel/#trs-tool-and-trs-tool-version-ids */
            path: {
                tool_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["ToolVersion"][]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__index: {
        /**
         * Index
         * @description Get a list of repositories or perform a search.
         */
        parameters?: {
            query?: {
                q?: string
                page?: number
                page_size?: number
                deleted?: boolean
                owner?: string
                name?: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json":
                        | components["schemas"]["RepositorySearchResults"]
                        | components["schemas"]["Repository"][]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__create: {
        /**
         * Create
         * @description create a new repository
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["Repository"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__get_ordered_installable_revisions: {
        /**
         * Get Ordered Installable Revisions
         * @description Get an ordered list of the repository changeset revisions that are installable
         */
        parameters?: {
            query?: {
                owner?: string
                name?: string
                tsr_id?: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": string[]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__legacy_install_info: {
        /**
         * Legacy Install Info
         * @description Get information used by the install client to install this repository.
         */
        parameters: {
            /** @description Name of the target repository. */
            /** @description Owner of the target repository. */
            /** @description Changeset of the target repository. */
            query: {
                name: string
                owner: string
                changeset_revision: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": Record<string, never>[]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__install_info: {
        /**
         * Install Info
         * @description Get information used by the install client to install this repository.
         */
        parameters: {
            /** @description Name of the target repository. */
            /** @description Owner of the target repository. */
            /** @description Changeset of the target repository. */
            query: {
                name: string
                owner: string
                changeset_revision: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["InstallInfo"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__reset_legacy: {
        /**
         * Reset Metadata On Repository Legacy
         * @description reset metadata on a repository
         */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["ResetMetadataOnRepositoryResponse"]
                }
            }
        }
    }
    repositories__update: {
        /** Updates */
        parameters: {
            query: {
                owner?: string
                name?: string
                changeset_revision: string
                hexlify?: boolean
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": Record<string, never>
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__show: {
        /** Show */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["DetailedRepository"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__show_allow_push: {
        /** Show Allow Push */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": string[]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__add_allow_push: {
        /** Add Allow Push */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            /** @description The target username. */
            path: {
                encoded_repository_id: string
                username: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": string[]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__remove_allow_push: {
        /** Remove Allow Push */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            /** @description The target username. */
            path: {
                encoded_repository_id: string
                username: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": string[]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__create_revision: {
        /**
         * Create Changeset Revision
         * @description upload new revision to the repository
         */
        parameters: {
            /** @description Set commit message as a query parameter. */
            query?: {
                commit_message?: string
            }
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_repositories__create_revision"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["RepositoryUpdate"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__set_deprecated: {
        /** Set Deprecated */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            204: never
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__unset_deprecated: {
        /** Unset Deprecated */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            204: never
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__metadata: {
        /**
         * Metadata
         * @description Get information about repository metadata
         */
        parameters: {
            /** @description Include only downloadable repositories. */
            query?: {
                downloadable_only?: boolean
            }
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": Record<string, never>
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__permissions: {
        /** Permissions */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["RepositoryPermissions"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__reset: {
        /**
         * Reset Metadata On Repository
         * @description reset metadata on a repository
         */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["ResetMetadataOnRepositoryResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__set_malicious: {
        /** Set Malicious */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            /** @description The changeset revision corresponding to the target revision of the target repository. */
            path: {
                encoded_repository_id: string
                changeset_revision: string
            }
        }
        responses: {
            /** @description Successful Response */
            204: never
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__unset_malicious: {
        /** Unset Malicious */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            /** @description The changeset revision corresponding to the target revision of the target repository. */
            path: {
                encoded_repository_id: string
                changeset_revision: string
            }
        }
        responses: {
            /** @description Successful Response */
            204: never
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__readmes: {
        /**
         * Get Readmes
         * @description fetch readmes for repository revision
         */
        parameters: {
            /** @description The encoded database identifier of the repository. */
            /** @description The changeset revision corresponding to the target revision of the target repository. */
            path: {
                encoded_repository_id: string
                changeset_revision: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["RepositoryRevisionReadmes"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    tools__index: {
        /** Index */
        parameters: {
            query: {
                q: string
                page?: number
                page_size?: number
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": Record<string, never>
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    tools__build_search_index: {
        /**
         * Build Search Index
         * @description Not part of the stable API, just something to simplify
         * bootstrapping tool sheds, scripting, testing, etc...
         */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["BuildSearchIndexResponse"]
                }
            }
        }
    }
    users__index: {
        /**
         * Index
         * @description index users
         */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["UserV2"][]
                }
            }
        }
    }
    users__create: {
        /**
         * Create
         * @description create a user
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["UserV2"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    users__current: {
        /**
         * Current
         * @description show current user
         */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["UserV2"]
                }
            }
        }
    }
    users__show: {
        /**
         * Show
         * @description show a user
         */
        parameters: {
            /** @description The encoded database identifier of the user. */
            path: {
                encoded_user_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["UserV2"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    users__get_or_create_api_key: {
        /** Return the user's API key */
        parameters: {
            /** @description The encoded database identifier of the user. */
            path: {
                encoded_user_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": string
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    users__create_api_key: {
        /** Creates a new API key for the user */
        parameters: {
            /** @description The encoded database identifier of the user. */
            path: {
                encoded_user_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": string
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    users__delete_api_key: {
        /** Delete the current API key of the user */
        parameters: {
            /** @description The encoded database identifier of the user. */
            path: {
                encoded_user_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            204: never
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    configuration__version: {
        /** Version */
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["Version"]
                }
            }
        }
    }
    users__internal_change_password: {
        /**
         * Change Password
         * @description reset a user
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UiChangePasswordRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            204: never
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    users__internal_login: {
        /**
         * Internal Login
         * @description login to web UI
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UiLoginRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["UiLoginResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    users__internal_logout: {
        /**
         * Internal Logout
         * @description logout of web UI
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UiLogoutRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["UiLogoutResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    users__internal_register: {
        /**
         * Register
         * @description register a user
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UiRegisterRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["UiRegisterResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    repositories__internal_metadata: {
        /**
         * Metadata Internal
         * @description Get information about repository metadata
         */
        parameters: {
            /** @description Include only downloadable repositories. */
            query?: {
                downloadable_only?: boolean
            }
            /** @description The encoded database identifier of the repository. */
            path: {
                encoded_repository_id: string
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": components["schemas"]["RepositoryMetadata"]
                }
            }
            /** @description Validation Error */
            422: {
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
}
