"""Manager for persisting data analysis chat execution artifacts."""

import mimetypes
from typing import Optional

from galaxy.exceptions import (
    InternalServerError,
    ObjectInvalid,
    ObjectNotFound,
    RequestParameterInvalidException,
)
from galaxy.managers.agents import AgentService
from galaxy.managers.chat import ChatManager
from galaxy.managers.context import ProvidesHistoryContext
from galaxy.model import HistoryDatasetAssociation
from galaxy.schema.agents import UploadedArtifact


def _guess_extension(filename: Optional[str], mime_type: Optional[str]) -> str:
    if filename and "." in filename:
        candidate = filename.rsplit(".", 1)[1].strip().lower()
        if candidate:
            return candidate
    if mime_type:
        guessed = mimetypes.guess_extension(mime_type)
        if guessed:
            return guessed.lstrip(".")
    return "data"


class DataAnalysisChatArtifactsManager:
    """Persist artifacts generated by browser-side data analysis execution."""

    def __init__(self, agent_service: AgentService, chat_manager: ChatManager):
        self.agent_service = agent_service
        self.chat_manager = chat_manager

    def create_artifact(
        self,
        exchange_id: int,
        trans: ProvidesHistoryContext,
        raw_bytes: bytes,
        name: str,
        mime_type: str,
        size: Optional[int] = None,
    ) -> UploadedArtifact:
        exchange = self.chat_manager.get_exchange_by_id(trans, exchange_id)
        if exchange is None:
            raise ObjectNotFound("Chat exchange not found")

        history = trans.history
        if history is None:
            raise RequestParameterInvalidException("No active history available")
        if not raw_bytes:
            raise RequestParameterInvalidException("Artifact contains no data")

        artifact_size = size if size is not None else len(raw_bytes)
        extension = _guess_extension(name, mime_type)

        hda = HistoryDatasetAssociation(
            history=history,
            name=name,
            extension=extension,
            create_dataset=True,
            sa_session=trans.sa_session,
        )
        trans.sa_session.add(hda)
        history.add_dataset(hda, set_hid=True)

        permissions = trans.app.security_agent.history_get_default_permissions(history)
        trans.app.security_agent.set_all_dataset_permissions(hda.dataset, permissions, new=True, flush=False)

        try:
            trans.app.object_store.create(hda.dataset)
            with open(hda.dataset.get_file_name(), "wb") as handle:
                handle.write(raw_bytes)

            hda.state = hda.states.OK
            hda.set_size()
            hda.set_total_size()
            hda.set_meta()
            hda.set_peek()

            trans.sa_session.flush()
            trans.sa_session.commit()
        except ObjectInvalid as exc:
            trans.sa_session.rollback()
            raise InternalServerError("Unable to create artifact dataset: object store is full.") from exc
        except Exception as exc:
            trans.sa_session.rollback()
            raise InternalServerError(f"Unable to persist artifact dataset: {exc}") from exc

        encoded_dataset_id = trans.security.encode_id(hda.id)
        return UploadedArtifact(
            dataset_id=encoded_dataset_id,
            history_id=trans.security.encode_id(history.id),
            name=name,
            mime_type=mime_type,
            size=artifact_size,
            download_url=self.agent_service._dataset_download_url(trans, encoded_dataset_id),
        )
