menu_bg.png : 
	./gradient.py 9 1000 DDDDFF 9999FF FFFFFF 0 0 FFFFFF 1 1 > $@

base_bg.png : 
	./gradient.py 9 1000 EEEEFF - FFFFFF 0 0 FFFFFF 1 1 > $@

masthead_bg.png : 
	./gradient.py 9 50 023858 000000 000000 0 0.5 000000 1 1 > $@

footer_title_bg.png : 
	./gradient.py 9 30 023858 000000 000000 0 0.5 000000 1 1 > $@

form_title_bg.png : 
	./gradient.py 9 50 ebd9b2 b9a780 FFFFFF 0 0 FFFFFF 0.5 1 > $@

ok_bg.png : 
	./gradient.py 9 200 AAFFAA - CCFFCC 0 0.5 CCFFCC 1 1 > $@

error_bg.png : 
	./gradient.py 9 200 FFAAAA - FFCCCC 0 0.5 FFCCCC 1 1 > $@

warn_bg.png : 
	./gradient.py 9 200 FFFFAA - FFFFCC 0 0.5 FFFFCC 1 1 > $@

gray_bg.png : 
	./gradient.py 9 200 AAAAAA - CCCCCC 0 0.5 CCCCCC 1 1 > $@
