# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ga4gh/data-repository-service-schemas/master/openapi/components/schemas/AccessURL.yaml
#   timestamp: 2022-05-21T22:19:11+00:00

from __future__ import annotations

from typing import (
    List,
    Optional,
)

from pydantic import (
    BaseModel,
    Field,
)


class Model(BaseModel):
    url: str = Field(..., description="A fully resolvable URL that can be used to fetch the actual object bytes.")
    headers: Optional[List[str]] = Field(
        None,
        description="An optional list of headers to include in the HTTP request to `url`. These headers can be used to provide auth tokens required to fetch the object bytes.",
        example="Authorization: Basic Z2E0Z2g6ZHJz",
    )
