# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ga4gh/data-repository-service-schemas/master/openapi/components/schemas/DrsService.yaml
#   timestamp: 2022-05-21T22:19:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import (
    BaseModel,
    Field,
)


class Artifact(Enum):
    drs = "drs"


class Type(BaseModel):
    artifact: Artifact = Field(..., example="drs")


class Model(BaseModel):
    type: Type
