# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ga4gh/data-repository-service-schemas/master/openapi/components/schemas/Error.yaml
#   timestamp: 2022-05-21T22:19:10+00:00

from __future__ import annotations

from typing import Optional

from pydantic import (
    BaseModel,
    Field,
)


class Model(BaseModel):
    msg: Optional[str] = Field(None, description="A detailed error message.")
    status_code: Optional[int] = Field(
        None, description="The integer representing the HTTP status code (e.g. 200, 404)."
    )
