"""
Pydantic schemas for AI agent responses and requests.
"""

from enum import Enum
from typing import (
    Any,
    Optional,
)

from pydantic import (
    BaseModel,
    Field,
    field_validator,
    model_validator,
)

from galaxy.schema.fields import (
    EncodedDatabaseIdField,
    ensure_valid_id,
)


class ConfidenceLevel(str, Enum):
    """Confidence levels for agent responses."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ActionType(str, Enum):
    """Types of actions agents can suggest."""

    TOOL_RUN = "tool_run"
    SAVE_TOOL = "save_tool"
    CONTACT_SUPPORT = "contact_support"
    VIEW_EXTERNAL = "view_external"
    DOCUMENTATION = "documentation"
    REFINE_QUERY = "refine_query"
    PYODIDE_EXECUTE = "pyodide_execute"


class ActionSuggestion(BaseModel):
    """Structured suggestion for user action."""

    action_type: ActionType = Field(description="Type of action to take")
    description: str = Field(description="Human-readable description of the action")
    parameters: dict[str, Any] = Field(default_factory=dict, description="Parameters for the action")
    confidence: ConfidenceLevel = Field(description="Confidence in this suggestion")
    priority: int = Field(default=1, description="Priority level (1=high, 2=medium, 3=low)")

    @model_validator(mode="after")
    def validate_parameters(self) -> "ActionSuggestion":
        """Ensure required parameters exist for each action type."""
        if self.action_type == ActionType.TOOL_RUN:
            if not self.parameters.get("tool_id"):
                raise ValueError("TOOL_RUN requires 'tool_id' parameter")
        elif self.action_type == ActionType.SAVE_TOOL:
            if not self.parameters.get("tool_yaml"):
                raise ValueError("SAVE_TOOL requires 'tool_yaml' parameter")
        elif self.action_type == ActionType.VIEW_EXTERNAL:
            if not self.parameters.get("url"):
                raise ValueError("VIEW_EXTERNAL requires 'url' parameter")
        return self


class AnalysisStepType(str, Enum):
    """Types of analysis steps taken by agents."""

    THOUGHT = "thought"
    ACTION = "action"
    OBSERVATION = "observation"
    CONCLUSION = "conclusion"


class AnalysisStepStatus(str, Enum):
    """Status of an analysis step."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    ERROR = "error"


class AnalysisStep(BaseModel):
    """Structured representation of a step in the agent's reasoning process."""

    type: AnalysisStepType = Field(description="Type of analysis step")
    content: str = Field(description="Content of the step")
    requirements: Optional[list[str]] = Field(
        default=None, description="Any requirements or dependencies for this step"
    )
    status: Optional[AnalysisStepStatus] = Field(default=None, description="Current status of this step")
    stdout: Optional[str] = Field(default=None, description="Captured standard output from this step")
    stderr: Optional[str] = Field(default=None, description="Captured standard error from this step")
    success: Optional[bool] = Field(default=None, description="Whether this step completed successfully")


class UploadedArtifact(BaseModel):
    """Representation of a Pyodide artifact generated by an agent."""

    dataset_id: str = Field(
        ...,
        title="Dataset ID",
        description="The encoded ID of the dataset created to store this artifact",
    )
    history_id: str = Field(
        ...,
        title="History ID",
        description="The encoded ID of the history where the dataset was created",
    )
    name: str = Field(description="Human-readable name of the artifact")
    mime_type: str = Field(description="MIME type of the artifact")
    size: int = Field(description="Size of the artifact in bytes")
    download_url: str = Field(description="URL to download the artifact content")

    @field_validator("dataset_id", "history_id")
    @classmethod
    def validate_encoded_id(cls, value: str) -> str:
        return ensure_valid_id(value)


class Artifact(BaseModel):
    """Artifact generated during execution of agent-produced code."""

    name: str = Field(description="Human readable artifact name")
    mime_type: str = Field(description="Artifact MIME type")
    size: int = Field(description="Artifact size in bytes")
    content_base64: Optional[str] = Field(default=None, description="Base64 content when small enough to inline")
    temp_path: Optional[str] = Field(default=None, description="Temporary server-side path for larger artifacts")


class ExecutionResult(BaseModel):
    """Result returned after executing a task."""

    task_id: Optional[str] = Field(default=None, description="Identifier of the task that produced this result")
    stdout: str = Field(default="", description="Captured standard output")
    stderr: str = Field(default="", description="Captured standard error")
    artifacts: list[Artifact] = Field(default_factory=list, description="Artifacts generated during execution")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional execution metadata")
    success: bool = Field(default=True, description="Whether execution completed successfully")


class HandoffInfo(BaseModel):
    """Information about handoff between agents."""

    source_agent: str = Field(description="Identifier of the agent initiating the handoff")
    target_agent: str = Field(description="Identifier of the agent receiving the handoff")


class PyodideStatus(str, Enum):
    """Status of Pyodide code execution."""

    COMPLETED = "completed"
    ERROR = "error"
    PENDING = "pending"
    TIMEOUT = "timeout"


class PyodideTaskConfig(BaseModel):
    """Additional configuration for Pyodide tasks."""

    index_url: str = Field(description="Custom package index URL for Pyodide to use when installing dependencies")


class PyodideFile(BaseModel):
    """Representation of a file to be provided in the Pyodide environment."""

    id: str = Field(description="Unique identifier for the file")
    name: Optional[str] = Field(default=None, description="Human-readable name of the file")
    size: Optional[int] = Field(default=None, description="Size of the file in bytes")
    aliases: list[str] = Field(default_factory=list, description="List of alternative names or aliases for the file")
    url: Optional[str] = Field(default=None, description="URL to fetch the file content from")
    mime_type: Optional[str] = Field(default=None, description="MIME type of the file")


class PyodideTask(BaseModel):
    """Structured representation of a Pyodide code execution task."""

    task_id: str = Field(description="Unique identifier for the task")
    action: str = Field(description="Action to perform, e.g. 'ExecutePythonInBrowser'")
    code: str = Field(description="Python code to execute in the browser")
    original_code: Optional[str] = Field(default=None, description="Original (unsanitized) Python code")
    packages: list[str] = Field(default_factory=list, description="List of Python packages required for execution")
    files: list[PyodideFile] = Field(
        default_factory=list, description="List of Pyodide files to be made available during execution"
    )
    timeout_ms: int = Field(default=120000, description="Execution timeout in milliseconds")
    alias_map: dict[str, str] = Field(
        default_factory=dict, description="Mapping of dataset IDs to human-readable aliases"
    )
    config: Optional[PyodideTaskConfig] = Field(
        default=None, description="Additional configuration for the Pyodide task"
    )


class DatasetDescriptor(BaseModel):
    """Description of a dataset available in the Pyodide execution environment."""

    id: str = Field(description="Encoded dataset ID")
    name: Optional[str] = Field(default=None, description="Human-readable dataset name")
    size: Optional[int] = Field(default=None, description="Dataset size in bytes")
    aliases: list[str] = Field(default_factory=list, description="Alternative names for this dataset")
    path: Optional[str] = Field(default=None, description="Server-side file path (not exposed to client)")


class PyodideContext(BaseModel):
    """Context stored alongside a pending Pyodide task, used to process the execution result."""

    alias_map: dict[str, str] = Field(default_factory=dict, description="Mapping of dataset IDs to aliases")
    datasets: list[DatasetDescriptor] = Field(default_factory=list, description="Datasets available for execution")
    requirements: list[str] = Field(default_factory=list, description="Python packages required for execution")


class ExecutionTask(BaseModel):
    """Previously executed Pyodide task, stored in response metadata for refinement on subsequent turns."""

    task_id: Optional[str] = Field(default=None, description="Identifier of the executed task")
    code: str = Field(default="", description="Python code that was executed")
    requirements: list[str] = Field(default_factory=list, description="Packages used during execution")
    datasets: list[DatasetDescriptor] = Field(default_factory=list, description="Datasets used during execution")
    alias_map: dict[str, str] = Field(default_factory=dict, description="Dataset alias map used during execution")
    timeout_seconds: Optional[int] = Field(default=None, description="Execution timeout in seconds")


class ResponseMetadata(BaseModel):
    """Additional metadata for agent responses."""

    analysis_steps: Optional[list[AnalysisStep]] = Field(
        default=None, description="Detailed reasoning steps taken by the agent"
    )
    artifacts: Optional[list[UploadedArtifact]] = Field(
        default=None, description="Artifacts generated during the agent's processing"
    )
    completion_state: Optional[str] = Field(
        default=None, description="Completion state of the response: 'complete', 'pending', or 'error'"
    )
    datasets_used: Optional[list[EncodedDatabaseIdField]] = Field(
        default=None, description="List of dataset IDs used in the agent's response"
    )
    error: Optional[str] = Field(default=None, description="Error message if any error occurred during processing")
    executed_task: Optional[ExecutionTask] = Field(
        default=None, description="Record of the previously executed Pyodide task, used for refinement"
    )
    execution: Optional[ExecutionResult] = Field(default=None, description="Result of the Pyodide execution")
    expected_files: Optional[list[str]] = Field(default=None, description="File outputs expected by the analysis plan")
    expected_plots: Optional[list[str]] = Field(default=None, description="Plot outputs expected by the analysis plan")
    fallback: Optional[bool] = Field(default=None, description="Whether this is a fallback response")
    files: Optional[list[str]] = Field(default=None, description="List of file names generated by the agent")
    handoff_info: Optional[HandoffInfo] = Field(default=None, description="Information about handoff between agents")
    input_tokens: Optional[int] = Field(default=None, description="Input token count for this response")
    is_complete: Optional[bool] = Field(
        default=None,
        description="Whether the agent considers its response complete or if further interaction is expected",
    )
    method: Optional[str] = Field(default=None, description="Internal method used to generate this response")
    model: Optional[str] = Field(default=None, description="LLM model used to generate the response")
    output_tokens: Optional[int] = Field(default=None, description="Output token count for this response")
    planner: Optional[str] = Field(default=None, description="Planner used to generate the analysis plan")
    planning_error: Optional[str] = Field(default=None, description="Error message from the planning phase")
    plots: Optional[list[str]] = Field(default=None, description="List of plot URLs generated by the agent")
    pyodide_context: Optional[PyodideContext] = Field(
        default=None, description="Context required to process the Pyodide execution result on the next turn"
    )
    pyodide_started_at: Optional[str] = Field(
        default=None, description="ISO 8601 timestamp of when the Pyodide task was dispatched"
    )
    pyodide_status: Optional[PyodideStatus] = Field(default=None, description="Status of any Pyodide code execution")
    pyodide_task: Optional[PyodideTask] = Field(default=None, description="Details of any Pyodide task")
    pyodide_timeout_reason: Optional[str] = Field(default=None, description="Reason for Pyodide timeout if applicable")
    pyodide_timeout_seconds: Optional[int] = Field(default=None, description="Seconds until Pyodide timeout")
    pyodide_retry_count: Optional[int] = Field(
        default=None, description="Number of retries attempted for Pyodide execution"
    )
    routed_by: Optional[str] = Field(default=None, description="Agent that routed this request")
    router_method: Optional[str] = Field(default=None, description="Routing method used to select the agent")
    stderr: Optional[str] = Field(default=None, description="Captured standard error from any code execution")
    stdout: Optional[str] = Field(default=None, description="Captured standard output from any code execution")
    summary: Optional[str] = Field(default=None, description="Summary of the agent's response or reasoning")
    tool_yaml: Optional[str] = Field(default=None, description="YAML definition of any tool generated by the agent")
    total_tokens: Optional[int] = Field(default=None, description="Total tokens used in generating the response")


class AgentResponse(BaseModel):
    """Structured response from an AI agent."""

    content: str = Field(description="Main response content")
    confidence: ConfidenceLevel = Field(description="Confidence in the response")
    agent_type: str = Field(description="Type of agent that generated this response")
    suggestions: list[ActionSuggestion] = Field(default_factory=list, description="Actionable suggestions")
    metadata: ResponseMetadata = Field(description="Additional metadata")
    reasoning: Optional[str] = Field(default=None, description="Explanation of the agent's reasoning")


class AgentQueryRequest(BaseModel):
    """Request to query an AI agent.

    DEPRECATED: Use /api/chat instead for new integrations.
    """

    query: str = Field(description="The user's question or request")
    agent_type: str = Field(default="auto", description="Preferred agent type ('auto' for routing)")
    context: dict[str, Any] = Field(default_factory=dict, description="Additional context for the query")


class AgentQueryResponse(BaseModel):
    """Response from an AI agent query.

    DEPRECATED: Use /api/chat instead for new integrations.
    """

    response: AgentResponse = Field(description="The agent's response")
    processing_time: Optional[float] = Field(default=None, description="Time taken to process the query in seconds")


class AvailableAgent(BaseModel):
    """Information about an available agent."""

    agent_type: str = Field(description="Unique identifier for the agent")
    name: str = Field(description="Human-readable name")
    description: str = Field(description="Description of the agent's capabilities")
    enabled: bool = Field(description="Whether the agent is currently enabled")
    model: Optional[str] = Field(default=None, description="LLM model used by the agent")
    specialties: list[str] = Field(default_factory=list, description="Areas of specialization")


class AgentListResponse(BaseModel):
    """Response listing available agents."""

    agents: list[AvailableAgent] = Field(description="List of available agents")
    total_count: int = Field(description="Total number of agents")


class RoutingDecision(BaseModel):
    """Decision made by the router agent."""

    primary_agent: str = Field(description="Primary agent to handle the query")
    secondary_agents: list[str] = Field(default_factory=list, description="Additional agents that might help")
    complexity: str = Field(description="Query complexity assessment")
    confidence: ConfidenceLevel = Field(description="Confidence in the routing decision")
    reasoning: str = Field(description="Explanation for the routing choice")
    direct_response: str = Field(default="", description="Direct response if routing is not needed")


class ErrorAnalysisRequest(BaseModel):
    """Request for error analysis."""

    query: str = Field(description="Description of the error or problem")
    job_id: Optional[int] = Field(default=None, description="Galaxy job ID associated with the error")
    error_text: Optional[str] = Field(default=None, description="Specific error message text")
    tool_id: Optional[str] = Field(default=None, description="Tool that caused the error")


class ErrorCategory(BaseModel):
    """Classification of error types."""

    category: str = Field(description="Main error category")
    subcategory: Optional[str] = Field(default=None, description="More specific error subcategory")
    severity: str = Field(description="Error severity level")


class ErrorAnalysisResponse(BaseModel):
    """Response from error analysis."""

    error_category: ErrorCategory = Field(description="Classification of the error")
    likely_cause: str = Field(description="Most probable cause of the error")
    solution_steps: list[str] = Field(description="Step-by-step solution")
    alternative_approaches: list[str] = Field(default_factory=list, description="Alternative solutions")
    confidence: ConfidenceLevel = Field(description="Confidence in the analysis")
    related_documentation: list[str] = Field(default_factory=list, description="Relevant documentation links")
    requires_admin: bool = Field(default=False, description="Whether admin intervention is needed")


class DatasetAnalysisRequest(BaseModel):
    """Request for dataset quality analysis."""

    dataset_id: str = Field(description="Galaxy dataset identifier")
    analysis_type: str = Field(default="comprehensive", description="Type of analysis to perform")
    focus_areas: list[str] = Field(default_factory=list, description="Specific areas to focus on")


class QualityIssue(BaseModel):
    """Description of a data quality issue."""

    issue_type: str = Field(description="Type of quality issue")
    severity: str = Field(description="Severity level")
    description: str = Field(description="Detailed description of the issue")
    suggested_fix: str = Field(description="Recommended solution")
    affected_records: Optional[int] = Field(default=None, description="Number of affected records")


class DatasetAnalysisResponse(BaseModel):
    """Response from dataset quality analysis."""

    quality_score: float = Field(description="Overall quality score (0.0 to 1.0)")
    issues_found: list[QualityIssue] = Field(description="List of quality issues detected")
    recommendations: list[str] = Field(description="General recommendations for improvement")
    preprocessing_steps: list[str] = Field(description="Suggested preprocessing steps")
    confidence: ConfidenceLevel = Field(description="Confidence in the analysis")


class WorkflowOptimizationRequest(BaseModel):
    """Request for workflow optimization."""

    workflow_id: Optional[str] = Field(default=None, description="Galaxy workflow identifier")
    workflow_structure: Optional[dict[str, Any]] = Field(default=None, description="Workflow structure data")
    performance_goals: list[str] = Field(default_factory=list, description="Optimization goals")


class OptimizationSuggestion(BaseModel):
    """Suggestion for workflow optimization."""

    suggestion_type: str = Field(description="Type of optimization")
    description: str = Field(description="Detailed description of the suggestion")
    expected_benefit: str = Field(description="Expected improvement")
    implementation_difficulty: str = Field(description="Difficulty level to implement")
    priority: int = Field(description="Priority level")


class WorkflowOptimizationResponse(BaseModel):
    """Response from workflow optimization analysis."""

    optimization_suggestions: list[OptimizationSuggestion] = Field(description="List of optimization suggestions")
    performance_improvements: list[str] = Field(description="Expected performance improvements")
    bottlenecks_identified: list[str] = Field(description="Identified bottlenecks")
    estimated_time_savings: Optional[str] = Field(default=None, description="Estimated time savings")
    confidence: ConfidenceLevel = Field(description="Confidence in the analysis")


class AgentMetrics(BaseModel):
    """Metrics for agent performance monitoring."""

    agent_type: str = Field(description="Type of agent")
    total_queries: int = Field(description="Total number of queries processed")
    success_rate: float = Field(description="Success rate (0.0 to 1.0)")
    average_response_time: float = Field(description="Average response time in seconds")
    confidence_distribution: dict[str, int] = Field(description="Distribution of confidence levels")
    last_update: str = Field(description="Last update timestamp")


class AgentStatus(BaseModel):
    """Current status of an agent."""

    agent_type: str = Field(description="Type of agent")
    enabled: bool = Field(description="Whether the agent is enabled")
    health_status: str = Field(description="Health status (healthy, degraded, unavailable)")
    last_response_time: Optional[float] = Field(default=None, description="Last response time in seconds")
    error_rate: float = Field(description="Recent error rate")
    model_info: dict[str, Any] = Field(default_factory=dict, description="Information about the underlying model")


class SystemStatus(BaseModel):
    """Overall system status for all agents."""

    total_agents: int = Field(description="Total number of registered agents")
    healthy_agents: int = Field(description="Number of healthy agents")
    agent_statuses: list[AgentStatus] = Field(description="Status of each agent")
    system_health: str = Field(description="Overall system health")
    last_check: str = Field(description="Last health check timestamp")
