# AUTOGENERATED by config_manage.py build_config_types — do not edit manually.
# Run `make config-rebuild` to regenerate from the config schema.


class ReportsAppConfigurationAttributes:
    """Type annotations for schema-defined "reports" config attributes."""

    log_level: str
    database_connection: str
    file_path: str
    new_file_path: str
    template_cache_path: str
    use_heartbeat: bool
    smtp_server: str
    error_email_to: str
    enable_beta_gdpr: bool
