# AUTOGENERATED by config_manage.py build_config_types — do not edit manually.
# Run `make config-rebuild` to regenerate from the config schema.
from typing import Any


class ToolShedAppConfigurationAttributes:
    """Type annotations for schema-defined "tool_shed" config attributes."""

    log_level: str
    database_connection: str
    hgweb_config_dir: str | None
    hgweb_repo_prefix: str
    config_hg_for_dev: str | None
    tool_shed_url: str | None
    file_path: str
    new_file_path: str
    builds_file_path: str
    pretty_datetime_format: str
    toolshed_search_on: bool
    whoosh_index_dir: str
    model_cache_dir: str
    repo_name_boost: float
    repo_description_boost: float
    repo_long_description_boost: float
    repo_homepage_url_boost: float
    repo_remote_repository_url_boost: float
    repo_owner_username_boost: float
    categories_boost: float
    tool_name_boost: float
    tool_description_boost: float
    tool_help_boost: float
    tool_repo_owner_username: float
    ga_code: str | None
    plausible_server: str | None
    plausible_domain: str | None
    matomo_server: str | None
    matomo_site_id: str | None
    id_secret: str
    use_remote_user: bool
    remote_user_secret: str
    remote_user_maildomain: str | None
    remote_user_header: str
    remote_user_logout_href: str | None
    admin_users: str | None
    require_login: bool
    allow_local_account_creation: bool
    allow_user_deletion: bool
    smtp_server: str | None
    email_from: str | None
    smtp_username: str | None
    smtp_password: str | None
    smtp_ssl: bool
    support_url: str
    mailing_join_addr: str
    ga4gh_service_id: str | None
    organization_name: str | None
    organization_url: str | None
    ga4gh_service_environment: str | None
    use_heartbeat: bool
    enable_galaxy_flavor_docker_image: bool
    message_box_visible: bool
    message_box_content: str | None
    message_box_class: str
    static_enabled: bool
    static_cache_time: int
    static_dir: str
    static_images_dir: str
    static_favicon_dir: str
    static_scripts_dir: str
    static_style_dir: str
    enable_beta_gdpr: bool
    apache_xsendfile: bool
    nginx_x_accel_redirect_base: str | None
    nginx_upload_path: str | None
    email_domain_blocklist_file: str | None
    email_domain_allowlist_file: str | None
    email_ban_file: str | None
    canonical_email_rules: Any
    brand: str | None
    citation_cache_type: str
    citation_cache_data_dir: str
    citation_cache_lock_dir: str
    citation_cache_url: str | None
    citation_cache_table_name: str
    citation_cache_schema_name: str | None
    log_actions: bool
    password_expiration_period: int
    sentry_dsn: str | None
    sentry_event_level: str
    sentry_traces_sample_rate: float
    sentry_ca_certs: str | None
    session_duration: int
    terms_url: str | None
    auth_config_file: str
    bootstrap_admin_api_key: str | None
    shed_tool_data_table_config: str
    datatypes_config_file: str
