[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version", "dependencies", "description", "readme", "requires-python", "optional-dependencies", "license", "authors"]
name = "galaxy-tool-util-models"
