FROM python:latest

RUN pip install --upgrade pip && \
    pip install galaxy-lib && \
    pip install galaxy-tool-util && \
    pip install galaxy-app && \
    pip install requests && \
    pip install requests-toolbelt && \
    pip install pulsar-galaxy-lib