module.exports = {
    createRouter: jest.fn(() => ({
        push: jest.fn(),
        replace: jest.fn(),
        go: jest.fn(),
        back: jest.fn(),
        forward: jest.fn(),
        beforeEach: jest.fn(),
        afterEach: jest.fn(),
        install: jest.fn(),
        resolve: jest.fn((route) => ({ href: `resolved-${route}` })),
    })),
    createWebHistory: jest.fn(() => ({
        base: "/",
        push: jest.fn(),
        replace: jest.fn(),
        go: jest.fn(),
        back: jest.fn(),
        forward: jest.fn(),
    })),
    createWebHashHistory: jest.fn(() => ({
        base: "/",
        push: jest.fn(),
        replace: jest.fn(),
        go: jest.fn(),
        back: jest.fn(),
        forward: jest.fn(),
    })),
    createMemoryHistory: jest.fn(() => ({
        base: "/",
        push: jest.fn(),
        replace: jest.fn(),
        go: jest.fn(),
        back: jest.fn(),
        forward: jest.fn(),
    })),
    useRoute: jest.fn(() => ({
        path: "/",
        params: {},
        query: {},
        hash: "",
        fullPath: "/",
        matched: [],
        meta: {},
        name: undefined,
    })),
    useRouter: jest.fn(() => ({
        push: jest.fn(),
        replace: jest.fn(),
        go: jest.fn(),
        back: jest.fn(),
        forward: jest.fn(),
        resolve: jest.fn((route) => ({ href: `resolved-${route}` })),
        currentRoute: {
            value: {
                path: "/",
                params: {},
                query: {},
                hash: "",
                fullPath: "/",
                matched: [],
                meta: {},
                name: undefined,
            },
        },
    })),
    RouterLink: {
        name: "RouterLink",
        props: ["to"],
        template: "<a><slot /></a>",
    },
    RouterView: {
        name: "RouterView",
        template: "<div />",
    },
};
