import 'script-loader!jquery'
import 'script-loader!./js/rna-viz'
import 'script-loader!underscore/underscore-min'
import 'script-loader!plotly.js/dist/plotly.min'
import 'script-loader!./js/visualize-alignment'
import 'script-loader!bootstrap/dist/js/bootstrap.min';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import './css/rna.viz.css'
