"""Render the user-defined tool authoring help into a Sphinx page.

The content lives in ``client/src/components/Tool/authoringHelp.yml`` so the
tool editor's help panel and this page stay the same text. See that file for
the authoring conventions; this script only reshapes it into MyST markdown.
"""

import re
import sys

import yaml

# Bodies link to other Galaxy docs with `gxdoc:<source path>` so they can render
# both here and in the editor. In the generated page the target is a path
# relative to doc/source/dev/; the editor resolves the same token to an absolute
# docs.galaxyproject.org URL.
GXDOC_LINK = re.compile(r"\]\(gxdoc:([^)]+)\)")

GENERATED_HEADER = """<!--
This page is generated by doc/gen_authoring_doc.py from
client/src/components/Tool/authoringHelp.yml, which is also what the tool
editor's help panel renders. Edit that file, not this one.
-->
"""


def resolve_links(text: str) -> str:
    return GXDOC_LINK.sub(lambda m: f"](../{m.group(1)})", text)


def render(help_data: dict) -> str:
    parts = [
        GENERATED_HEADER,
        f"# {help_data['title']}",
        "",
        resolve_links(help_data["intro"].rstrip()),
        "",
    ]
    groups = (("reference", "Reference"), ("faq", "Common questions"))
    for kind, title in groups:
        parts.append(f"## {title}")
        parts.append("")
        for section in help_data["sections"]:
            if section["kind"] != kind:
                continue
            parts.append(f"### {section['title']}")
            parts.append("")
            parts.append(resolve_links(section["body"].rstrip()))
            parts.append("")
    return "\n".join(parts) + "\n"


def main() -> None:
    with open(sys.argv[1]) as fh:
        help_data = yaml.safe_load(fh)
    sys.stdout.write(render(help_data))


if __name__ == "__main__":
    main()
