"""Render the user-defined tool authoring help into a Sphinx page.

The content lives in ``client/src/components/Tool/authoringHelp.yml`` so the
tool editor's help panel and this page stay the same text. See that file for
the authoring conventions; this script only reshapes it into MyST markdown.
"""

import json
import re
import sys
import textwrap
from pathlib import Path

import yaml

# Bodies link to other Galaxy docs with `gxdoc:<source path>` so they can render
# both here and in the editor. In the generated page the target is a path
# relative to doc/source/dev/; the editor resolves the same token to an absolute
# docs.galaxyproject.org URL.
GXDOC_LINK = re.compile(r"\]\(gxdoc:([^)]+)\)")
OUTPUT_TYPE_INDEX = "{{output_type_index}}"
PARAMETER_TYPE_INDEX = "{{parameter_type_index}}"
TOOL_SCHEMA_PATH = (
    Path(__file__).resolve().parents[1]
    / "client"
    / "src"
    / "components"
    / "Tool"
    / "ToolSourceSchema.json"
)

GENERATED_HEADER = """<!--
This page is generated by doc/gen_authoring_doc.py from
client/src/components/Tool/authoringHelp.yml, which is also what the tool
editor's help panel renders. Edit that file, not this one.
-->
"""


def resolve_links(text: str) -> str:
    return GXDOC_LINK.sub(lambda m: f"](../{m.group(1)})", text)


def _markdown_cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ")


def _property_details(prop: dict) -> str:
    details = []
    if description := prop.get("description"):
        details.append(description.strip())
    elif "const" in prop:
        details.append(f"Must be `{prop['const']}`.")
    else:
        types = [option["type"] for option in prop.get("anyOf", []) if "type" in option]
        if prop.get("type"):
            types.append(prop["type"])
        if types:
            details.append(
                "Type: " + " or ".join(f"`{type_name}`" for type_name in types) + "."
            )
    return _markdown_cell(" ".join(details) or "No additional constraints.")


def _property_default(prop: dict) -> str:
    if "default" not in prop:
        return "—"
    return f"`{json.dumps(prop['default'], separators=(',', ':'))}`"


def _field_table(definition: dict) -> list[str]:
    required = set(definition.get("required", []))
    return [
        "| Field | Details | Default | Required |",
        "| --- | --- | --- | --- |",
        *[
            f"| `{name}` | {_property_details(prop)} | {_property_default(prop)} | "
            f"{'Yes' if name in required else 'No'} |"
            for name, prop in definition.get("properties", {}).items()
        ],
    ]


def _schema_example(type_name: str, definition: dict) -> dict:
    examples = definition.get("examples", [])
    if not examples:
        raise ValueError(f"Schema '{type_name}' has no example.")
    return examples[0]


def _reference_index(label: str, prefix: str, sections: list[dict]) -> str:
    return "\n".join(
        [
            f"| {label} | Details |",
            "| --- | --- |",
            *[
                f"| [`{section['id'].removeprefix(f'{prefix}-')}`](#{section['id']}) | "
                f"{_markdown_cell(section['body'].splitlines()[0])} |"
                for section in sections
            ],
        ]
    )


def _build_parameter_type_reference(tool_schema: dict) -> tuple[str, list[dict]]:
    definitions = tool_schema["$defs"]
    mapping = definitions["YamlGalaxyToolParameter"]["discriminator"]["mapping"]
    sections = []
    for parameter_type, reference in mapping.items():
        definition_name = reference.rsplit("/", 1)[-1]
        definition = definitions[definition_name]
        example = _schema_example(parameter_type, definition)
        shell_command = definition.get("x-shell-command")
        if not shell_command:
            raise ValueError(
                f"Parameter schema '{parameter_type}' has no shell command example."
            )
        example_yaml = "inputs:\n" + textwrap.indent(
            yaml.safe_dump(
                [example],
                allow_unicode=True,
                sort_keys=False,
            ).rstrip(),
            "  ",
        )
        shell_command_yaml = "shell_command: |\n" + textwrap.indent(shell_command, "  ")
        description = definition.get("description", "").replace("``", "`").strip()
        section = {
            "id": f"parameter-{parameter_type}",
            "title": f"{parameter_type} parameter",
            "kind": "reference",
            "parent_id": "parameters",
            "body": "\n".join(
                [
                    description,
                    "",
                    *_field_table(definition),
                    "",
                    f"Add this `{parameter_type}` parameter under `inputs`:",
                    "",
                    "```yaml",
                    example_yaml,
                    "```",
                    "",
                    "Use the parameter in `shell_command` like this:",
                    "",
                    "```yaml",
                    shell_command_yaml,
                    "```",
                ]
            ),
        }
        sections.append(section)
    return _reference_index("Parameter type", "parameter", sections), sections


def _build_output_type_reference(tool_schema: dict) -> tuple[str, list[dict]]:
    definitions = tool_schema["$defs"]
    mapping = tool_schema["properties"]["outputs"]["items"]["discriminator"]["mapping"]
    sections = []
    for output_type, reference in mapping.items():
        definition_name = reference.rsplit("/", 1)[-1]
        definition = definitions[definition_name]
        example = _schema_example(output_type, definition)
        example_yaml = "outputs:\n" + textwrap.indent(
            yaml.safe_dump([example], allow_unicode=True, sort_keys=False).rstrip(),
            "  ",
        )
        description = definition.get("description", "").replace("``", "`").strip()
        sections.append(
            {
                "id": f"output-{output_type}",
                "title": f"{output_type} output",
                "kind": "reference",
                "parent_id": "outputs",
                "body": "\n".join(
                    [
                        description,
                        "",
                        *_field_table(definition),
                        "",
                        f"Add this `{output_type}` output under `outputs`:",
                        "",
                        "```yaml",
                        example_yaml,
                        "```",
                    ]
                ),
            }
        )
    return _reference_index("Output type", "output", sections), sections


def render(help_data: dict, tool_schema: dict) -> str:
    parameter_index, parameter_sections = _build_parameter_type_reference(tool_schema)
    output_index, output_sections = _build_output_type_reference(tool_schema)
    sections = []
    for raw_section in help_data["sections"]:
        section = dict(raw_section)
        has_parameter_types = section.pop("parameter_types", False)
        has_output_types = section.pop("output_types", False)
        section["body"] = section["body"].replace(PARAMETER_TYPE_INDEX, parameter_index)
        section["body"] = section["body"].replace(OUTPUT_TYPE_INDEX, output_index)
        sections.append(section)
        if has_parameter_types:
            sections.extend(parameter_sections)
        if has_output_types:
            sections.extend(output_sections)
    parts = [
        GENERATED_HEADER,
        f"# {help_data['title']}",
        "",
        resolve_links(help_data["intro"].rstrip()),
        "",
    ]
    groups = (("reference", "Reference"), ("faq", "Common questions"))
    for kind, title in groups:
        parts.append(f"## {title}")
        parts.append("")
        for section in sections:
            if section["kind"] != kind:
                continue
            parts.append(f'<span id="{section["id"]}"></span>')
            parts.append("")
            heading = "####" if section.get("parent_id") else "###"
            parts.append(f"{heading} {section['title']}")
            parts.append("")
            parts.append(resolve_links(section["body"].rstrip()))
            parts.append("")
    return "\n".join(parts) + "\n"


def main() -> None:
    with open(sys.argv[1]) as fh:
        help_data = yaml.safe_load(fh)
    with TOOL_SCHEMA_PATH.open() as fh:
        tool_schema = json.load(fh)
    sys.stdout.write(render(help_data, tool_schema))


if __name__ == "__main__":
    main()
