history_dataset_collection_id:
  - history_dataset_collection_display
history_dataset_id:
  - history_dataset_display
  - history_dataset_info
  - history_dataset_index
  - history_dataset_type
  - history_dataset_embedded
  - history_dataset_as_table
  - history_dataset_as_image
  - history_dataset_link
  - history_dataset_name
  - history_dataset_peek
  - visualization
history_id:
  - history_link
invocation_id:
  - invocation_inputs
  - invocation_outputs
  - invocation_time
job_id:
  - job_metrics
  - job_parameters
  - tool_stderr
  - tool_stdout
workflow_id:
  - workflow_display
  - workflow_image
  - workflow_license
none:
  - generate_galaxy_version
  - generate_time
  - instance_access_link
  - instance_citation_link
  - instance_help_link
  - instance_organization_link
  - instance_resources_link
  - instance_support_link
  - instance_terms_link
