ATTRS_FILENAME_HISTORY = "history_attrs.txt"
ATTRS_FILENAME_DATASETS = "datasets_attrs.txt"
ATTRS_FILENAME_JOBS = "jobs_attrs.txt"
ATTRS_FILENAME_IMPLICIT_COLLECTION_JOBS = "implicit_collection_jobs_attrs.txt"
ATTRS_FILENAME_COLLECTIONS = "collections_attrs.txt"
ATTRS_FILENAME_EXPORT = "export_attrs.txt"
ATTRS_FILENAME_LIBRARIES = "libraries_attrs.txt"
ATTRS_FILENAME_LIBRARY_FOLDERS = "library_folders_attrs.txt"
ATTRS_FILENAME_INVOCATIONS = "invocation_attrs.txt"
ATTRS_FILENAME_CONVERSIONS = "implicit_dataset_conversions.txt"

GALAXY_EXPORT_VERSION = "2"

MODEL_STORE_METADATA_FILENAMES = (
    ATTRS_FILENAME_HISTORY,
    ATTRS_FILENAME_DATASETS,
    f"{ATTRS_FILENAME_DATASETS}.provenance",
    ATTRS_FILENAME_JOBS,
    ATTRS_FILENAME_IMPLICIT_COLLECTION_JOBS,
    ATTRS_FILENAME_COLLECTIONS,
    ATTRS_FILENAME_CONVERSIONS,
    ATTRS_FILENAME_EXPORT,
    ATTRS_FILENAME_LIBRARIES,
    ATTRS_FILENAME_LIBRARY_FOLDERS,
    ATTRS_FILENAME_INVOCATIONS,
)
