import hashlib
import logging
import os
import re
from typing import (
    Any,
)

from rocrate.model.computationalworkflow import (
    ComputationalWorkflow,
    WorkflowDescription,
)
from rocrate.model.contextentity import ContextEntity
from rocrate.model.file import File
from rocrate.model.softwareapplication import SoftwareApplication
from rocrate.rocrate import ROCrate

from galaxy.model import (
    HistoryDatasetAssociation,
    HistoryDatasetCollectionAssociation,
    Workflow,
    WorkflowInvocation,
    WorkflowInvocationStep,
)
from galaxy.version import VERSION
from .model_store_constants import GALAXY_EXPORT_VERSION
from .ro_crate_metadata import is_publishable_metadata_field

logger = logging.getLogger(__name__)


PROFILES_VERSION = "0.5"
WROC_PROFILE_VERSION = "1.0"

RO_CRATE_PARAMETER_TYPES = {
    "integer": "Integer",
    "data_column": "Integer",
    "float": "Float",
    "boolean": "Boolean",
    "baseurl": "URL",
    "directory_uri": "URL",
    "file": "File",
    "ftpfile": "File",
    "data": "File",
    "hidden_data": "File",
    "library_data": "File",
    "data_collection": "Collection",
    "collection": "Collection",
    "rules": "PropertyValue",
    "text": "Text",
    "genomebuild": "Text",
    "select": "Text",
    "color": "Text",
    "group_tag": "Text",
    "hidden": "Text",
    "drill_down": "Text",
}

RO_CRATE_DATASET_STATUS_FIELDS = (
    "validated_state",
    "validated_state_message",
    "metadata_deferred",
    "visible",
    "deleted",
    "purged",
    "state",
)


def ro_crate_parameter_type(parameter_type: str | None) -> str:
    return RO_CRATE_PARAMETER_TYPES.get(parameter_type or "", "Thing")


class WorkflowRunCrateProfileBuilder:
    def __init__(self, model_store: Any):
        self.model_store = model_store
        self.invocation: WorkflowInvocation = model_store.included_invocations[0]
        self.workflow: Workflow = self.invocation.workflow
        self.workflow_entities: dict[int, Any] = {}
        self.collection_entities: dict[int, Any] = {}
        self.file_entities: dict[int, Any] = {}
        self.param_entities: dict[int, Any] = {}
        self.pv_entities: dict[str, Any] = {}
        # Cache for tools to avoid duplicating entities for the same tool
        self.tool_cache: dict[tuple[str | None, str | None], ContextEntity] = {}
        self.step_cache: dict[int, ContextEntity] = {}
        self.workflow_definitions: dict[int, ContextEntity] = {}
        self.invocation_actions: dict[int, ContextEntity] = {}
        self.engine_actions: dict[int, ContextEntity] = {}
        self.provenance_complete = False

    def build_crate(self):
        crate = ROCrate()
        crate.metadata.extra_contexts.append("https://w3id.org/ro/terms/workflow-run/context")
        invocation_time = (
            self.invocation.create_time.isoformat() if self.invocation.create_time else "an unrecorded time"
        )
        crate.name = f'Invocation of workflow "{self.workflow.name}" on {invocation_time}'
        crate.description = f'Invocation of Galaxy workflow "{self.workflow.name}" requested at {invocation_time}. This RO-Crate was automatically generated by Galaxy.'
        no_license_asserted = crate.add(
            ContextEntity(
                crate,
                "#license-not-specified",
                properties={
                    "@type": "CreativeWork",
                    "name": "No license asserted",
                    "description": "No separate license was supplied for this workflow invocation crate.",
                },
            )
        )
        crate.root_dataset["license"] = no_license_asserted
        galaxy_project = crate.add(
            ContextEntity(
                crate,
                "https://galaxyproject.org/",
                properties={"@type": "Organization", "name": "Galaxy Project", "url": "https://galaxyproject.org/"},
            )
        )
        galaxy_generator = crate.add(
            SoftwareApplication(
                crate,
                identifier=f"https://galaxyproject.org/version/{VERSION}",
                properties={
                    "name": "Galaxy",
                    "softwareVersion": VERSION,
                    "url": "https://galaxyproject.org/",
                },
            )
        )
        for key, value in self.model_store._date_properties(
            dateCreated=self.invocation.create_time, dateModified=self.invocation.update_time
        ).items():
            crate.root_dataset[key] = value
        crate.root_dataset["version"] = GALAXY_EXPORT_VERSION
        galaxy_generator["publisher"] = galaxy_project
        crate.root_dataset["sdPublisher"] = galaxy_generator
        crate.root_dataset["publisher"] = galaxy_project
        crate.root_dataset["author"] = galaxy_project
        crate.root_dataset["additionalProperty"] = crate.add(
            ContextEntity(
                crate,
                "#galaxy-export-scope",
                properties={
                    "@type": "PropertyValue",
                    "name": "Galaxy export scope",
                    "value": f"workflow invocation; included datasets={len(self.model_store.included_datasets)}; included jobs={len(self.model_store.included_jobs)}",
                },
            )
        )
        if self.invocation.uuid:
            crate.root_dataset["identifier"] = f"urn:uuid:{self.invocation.uuid}"
        self._add_workflows(crate)
        main_invocation, main_workflow = self.invocation, self.workflow
        for invocation in self.model_store.included_invocations:
            self.invocation, self.workflow = invocation, invocation.workflow
            self._add_create_action(crate)
            self._add_engine_run(crate)
            self.invocation_actions[invocation.id] = self.create_action
            self.engine_actions[invocation.id] = self.roc_engine_run
        self.invocation, self.workflow = main_invocation, main_workflow
        self.create_action = self.invocation_actions[main_invocation.id]
        self.roc_engine_run = self.engine_actions[main_invocation.id]
        self._add_collections(crate)
        self._add_files(crate)
        # Include intermediate and metadata-only datasets before linking job I/O.
        for dataset, _ in self.model_store.included_datasets.values():
            self._add_file(dataset, {}, crate)
        job_actions = self.model_store._add_job_provenance(crate, self.file_entities, link_outputs_to_actions=False)
        self.model_store._add_dataset_conversion_provenance(crate, self.file_entities)
        controlled_steps = self._add_step_execution_provenance(crate, job_actions)
        executable_steps = {
            step.id
            for invocation in self.model_store.included_invocations
            for step in invocation.steps
            if step.workflow_step.type in {"tool", "subworkflow"}
        }
        self.provenance_complete = bool(executable_steps) and executable_steps <= controlled_steps
        for invocation in self.model_store.included_invocations:
            self.invocation = invocation
            self.create_action = self.invocation_actions[invocation.id]
            self._add_parameters(crate)
        self.invocation = main_invocation
        self.create_action = self.invocation_actions[main_invocation.id]
        self._add_connections(crate)
        self._add_unbound_port_metadata(crate)
        self._add_invocation_diagnostics(crate)
        self.provenance_complete = self.provenance_complete and self._complete_execution_graph(job_actions)
        self._add_profiles(crate)
        self._add_readme(crate)
        self.model_store._add_galaxy_model_metadata_files(crate)
        self.model_store._add_instance_metadata(crate)
        return crate

    def _add_unbound_port_metadata(self, crate):
        referenced = set()
        for entity in crate.get_entities():
            values = entity.get("exampleOfWork") or []
            if not isinstance(values, list):
                values = [values]
            for value in values:
                identifier = value.id if hasattr(value, "id") else value.get("@id") if isinstance(value, dict) else None
                if identifier:
                    referenced.add(identifier)
        for parameter in crate.get_entities():
            if "FormalParameter" not in parameter.type or parameter.id in referenced:
                continue
            digest = hashlib.sha256(parameter.id.encode()).hexdigest()
            value = crate.add(
                ContextEntity(
                    crate,
                    f"#unbound-parameter-{digest}",
                    properties={
                        "@type": "PropertyValue",
                        "name": parameter.get("name") or "Unnamed parameter",
                        "description": "No direct invocation binding was recorded for this formal parameter.",
                        "exampleOfWork": parameter,
                    },
                )
            )
            crate.root_dataset.append_to("mentions", value)

    def _complete_execution_graph(self, job_actions):
        for invocation in self.model_store.included_invocations:
            scheduled = {step.workflow_step_id: step for step in invocation.steps}
            for definition in invocation.workflow.steps:
                if definition.type not in {"tool", "subworkflow"}:
                    continue
                execution = scheduled.get(definition.id)
                if execution is None:
                    return False
                if definition.type == "tool":
                    jobs = list(execution.jobs)
                    if not jobs or any(job.id not in job_actions or job.state == "skipped" for job in jobs):
                        return False
                    for job in jobs:
                        if (job.tool_id, job.tool_version) != (definition.tool_id, definition.tool_version):
                            return False
                        for association in [*job.input_datasets, *job.output_datasets]:
                            if association.dataset and getattr(association, "dataset_version", None) not in (
                                None,
                                association.dataset.version,
                            ):
                                return False
                            if association.dataset and association.dataset.dataset.id not in self.file_entities:
                                return False
        return True

    def _add_invocation_diagnostics(self, crate):
        for invocation in self.model_store.included_invocations:
            action = self.invocation_actions[invocation.id]
            for message in invocation.messages:
                properties = {"@type": "CreativeWork", "name": message.reason or "Galaxy invocation diagnostic"}
                if message.details and self.model_store._safe_metadata_value(message.details):
                    properties["description"] = message.details
                diagnostic = crate.add(ContextEntity(crate, f"#invocation-message-{message.id}", properties=properties))
                action.append_to("subjectOf", diagnostic)
                for field in ("output_name", "workflow_step_index_path"):
                    self.model_store._add_metadata_property(
                        crate, diagnostic, f"Galaxy {field}", getattr(message, field, None)
                    )
                references = [
                    self.step_cache.get(message.workflow_step_id),
                    self.step_cache.get(message.dependent_workflow_step_id),
                    crate.get(f"#galaxy-job-{message.job_id}"),
                ]
                for dataset, _ in self.model_store.included_datasets.values():
                    if isinstance(dataset, HistoryDatasetAssociation) and dataset.id == message.hda_id:
                        references.append(self.file_entities.get(dataset.dataset.id))
                for collection in self.model_store.included_collections.values():
                    if isinstance(collection, HistoryDatasetCollectionAssociation) and collection.id == message.hdca_id:
                        references.append(crate.get(f"#dataset-collection-{collection.collection.id}"))
                for reference in references:
                    if reference is not None and reference not in (diagnostic.get("about") or []):
                        diagnostic.append_to("about", reference)

    def _add_connections(self, crate):
        def port(step, direction, name):
            workflow = self.workflow_definitions[step.workflow_id]
            if step.type == "subworkflow" and step.subworkflow is not None:
                if direction == "output":
                    for output in step.subworkflow.workflow_outputs:
                        if name in (output.label, output.output_name):
                            for kind, suffix in (
                                ("output", ""),
                                ("collection-output", ""),
                                ("scalar-output", "-parameter"),
                            ):
                                existing = crate.get(
                                    f"#workflow-definition-{step.subworkflow_id}-{kind}-{output.id}{suffix}"
                                )
                                if existing is not None:
                                    return existing
                else:
                    for nested_step in step.subworkflow.steps:
                        if (
                            nested_step.type in {"data_input", "data_collection_input", "parameter_input"}
                            and nested_step.label == name
                        ):
                            return port(nested_step, "input", name)
            if step.type in {"data_input", "data_collection_input", "parameter_input"}:
                for invocation in self.model_store.included_invocations:
                    if invocation.workflow_id != step.workflow_id:
                        continue
                    for identifier in (
                        f"#workflow-definition-{step.workflow_id}-input-{step.id}",
                        f"#workflow-definition-{step.workflow_id}-collection-input-{step.id}",
                        f"#workflow-definition-{step.workflow_id}-parameter-{step.id}",
                    ):
                        existing = crate.get(identifier)
                        if existing is not None:
                            return existing
                owner, direction = workflow, "input"
            else:
                control = self.step_cache.get(step.id)
                owner = control.get("workExample") if control is not None else workflow
            identifier = hashlib.sha256(f"{owner.id}:{direction}:{name}".encode()).hexdigest()
            existing = crate.get(f"#port-{identifier}")
            if existing is not None:
                return existing
            entity = crate.add(
                ContextEntity(
                    crate,
                    f"#port-{identifier}",
                    properties={
                        "@type": "FormalParameter",
                        "name": name or step.label or "Unnamed port",
                        "additionalType": "Thing",
                    },
                )
            )
            owner.append_to(direction, entity)
            return entity

        visited = set()
        for invocation in self.model_store.included_invocations:
            workflow = invocation.workflow
            if workflow.id in visited:
                continue
            visited.add(workflow.id)
            for step in workflow.steps:
                for input_ in step.inputs:
                    target = port(step, "input", input_.name)
                    # These are workflow-step overrides, not defaults of the shared tool.
                    settings_owner = self.step_cache.get(step.id) or self.workflow_definitions[workflow.id]
                    for field in ("merge_type", "scatter_type", "value_from", "value_from_type"):
                        self.model_store._add_metadata_property(
                            crate, settings_owner, f"Galaxy input {input_.name} {field}", getattr(input_, field, None)
                        )
                    if input_.default_value_set and is_publishable_metadata_field(input_.name, input_.default_value):
                        self.model_store._add_metadata_property(
                            crate, settings_owner, f"Galaxy input {input_.name} default", input_.default_value
                        )
                    for connection in input_.connections:
                        if connection.non_data_connection:
                            self.model_store._add_metadata_property(
                                crate, target, "Galaxy non-data dependency step", connection.output_step_id
                            )
                            continue
                        source = port(connection.output_step, "output", connection.output_name)
                        connection_target = target
                        if connection.input_subworkflow_step is not None:
                            connection_target = port(
                                connection.input_subworkflow_step, "input", connection.input_subworkflow_step.label
                            )
                        entity = crate.add(
                            ContextEntity(
                                crate,
                                f"#parameter-connection-{connection.id}",
                                properties={
                                    "@type": "ParameterConnection",
                                    "sourceParameter": source,
                                    "targetParameter": connection_target,
                                },
                            )
                        )
                        receiver = self.step_cache.get(step.id) or self.workflow_definitions[workflow.id]
                        receiver.append_to("connection", entity)

        # Workflow outputs are connections from step/tool outputs to workflow ports.
        for invocation in self.model_store.included_invocations:
            workflow_entity = self.workflow_definitions[invocation.workflow_id]
            for kind, associations in (
                ("output", invocation.output_datasets),
                ("collection-output", invocation.output_dataset_collections),
                ("scalar-output", invocation.output_values),
            ):
                for association in associations:
                    output = association.workflow_output
                    suffix = "-parameter" if kind == "scalar-output" else ""
                    target = crate.get(f"#workflow-definition-{invocation.workflow_id}-{kind}-{output.id}{suffix}")
                    if target is None or output.workflow_step is None:
                        continue
                    source = port(output.workflow_step, "output", output.output_name)
                    example = None
                    if kind == "output" and association.dataset and association.dataset.dataset:
                        example = self.file_entities.get(association.dataset.dataset.id)
                    elif kind == "collection-output" and association.dataset_collection:
                        example = self.collection_entities.get(association.dataset_collection.collection.id)
                    elif kind == "scalar-output":
                        example = crate.get(f"#workflow-{invocation.id}-scalar-output-{output.id}")
                    if example is not None and source not in (example.get("exampleOfWork") or []):
                        example.append_to("exampleOfWork", source)
                        if "File" in example.type:
                            source["additionalType"] = "File"
                        elif "Dataset" in example.type:
                            source["additionalType"] = "Dataset"
                        elif "Collection" in example.type:
                            source["additionalType"] = "Collection"
                    identifier = f"#workflow-output-connection-{output.id}"
                    if crate.get(identifier) is None:
                        connection = crate.add(
                            ContextEntity(
                                crate,
                                identifier,
                                properties={
                                    "@type": "ParameterConnection",
                                    "sourceParameter": source,
                                    "targetParameter": target,
                                },
                            )
                        )
                        workflow_entity.append_to("connection", connection)

    def _add_file(
        self, dataset: HistoryDatasetAssociation, properties: dict[Any, Any], crate: ROCrate
    ) -> File | ContextEntity:
        assert dataset.dataset is not None
        existing = self.file_entities.get(dataset.dataset.id)
        if existing is not None:
            for key, value in properties.items():
                existing.append_to(key, value)
            return existing
        filename, extra_files_path = self.model_store.dataset_id_to_path.get(dataset.dataset.id, (None, None))
        source = os.path.join(self.model_store.export_directory, filename) if filename else None
        fair_properties = self.model_store._dataset_ro_crate_properties(dataset, source)
        fair_properties.update(properties)
        fair_properties["license"] = crate.get("#license-not-specified")
        fair_properties["conditionsOfAccess"] = (
            "The payload is embedded in this RO-Crate."
            if filename
            else "The payload is unavailable or excluded from this export; metadata is retained."
        )
        file_properties = fair_properties.copy()
        file_properties.pop("_galaxy_sha256", None)
        if filename:
            file_entity = crate.add_file(source, dest_path=filename, properties=file_properties)
        else:
            file_entity = crate.add(
                ContextEntity(
                    crate,
                    self.model_store._metadata_only_dataset_id(dataset),
                    properties={"@type": "Dataset", **file_properties},
                )
            )
            crate.root_dataset.append_to("hasPart", file_entity)
        self.model_store._attach_dataset_checksum(crate, file_entity, fair_properties)
        self.model_store._attach_dataset_metadata(crate, file_entity, dataset)
        self.model_store._add_composite_dataset_parts(crate, file_entity, extra_files_path)
        self.file_entities[dataset.dataset.id] = file_entity
        return file_entity

    def _add_files(self, crate: ROCrate):
        # Process all invocations (parent + subworkflows)
        for invocation in self.model_store.included_invocations:
            # Only add formal parameters for the main invocation
            workflow_entity = getattr(self, "workflow_definitions", {}).get(
                getattr(invocation, "workflow_id", None), crate.mainEntity
            )
            action = getattr(self, "invocation_actions", {}).get(invocation.id, self.create_action)

            for wfda in invocation.input_datasets:
                if wfda.dataset:
                    dataset_formal_param = self._add_dataset_formal_parameter(
                        wfda.dataset,
                        crate,
                        f"#workflow-definition-{getattr(invocation, 'workflow_id', invocation.id)}-input-{wfda.workflow_step_id}",
                        wfda.workflow_step.label,
                    )
                    workflow_entity.append_to("input", dataset_formal_param)
                    properties = {"exampleOfWork": {"@id": dataset_formal_param.id}}
                    file_entity = self._add_file(wfda.dataset, properties, crate)
                    action.append_to("object", file_entity)

            for wfda in invocation.output_datasets:
                if wfda.dataset:
                    dataset_formal_param = self._add_dataset_formal_parameter(
                        wfda.dataset,
                        crate,
                        f"#workflow-definition-{getattr(invocation, 'workflow_id', invocation.id)}-output-{wfda.workflow_output.id}",
                        wfda.workflow_output.label or wfda.workflow_output.output_name,
                    )
                    workflow_entity.append_to("output", dataset_formal_param)
                    properties = {"exampleOfWork": {"@id": dataset_formal_param.id}}
                    file_entity = self._add_file(wfda.dataset, properties, crate)
                    action.append_to("result", file_entity)

    def _add_collection(
        self, hdca: HistoryDatasetCollectionAssociation, crate: ROCrate, collection_formal_param: ContextEntity
    ) -> ContextEntity:
        for hda in hdca.dataset_instances:
            if hda.dataset:
                self._add_file(hda, {}, crate)
        if hdca.collection.id not in self.collection_entities:
            self.collection_entities.update(
                self.model_store._add_generic_collections(crate, self.file_entities, collections=[hdca])
            )
        collection_entity = self.collection_entities[hdca.collection.id]
        collection_entity.append_to("exampleOfWork", collection_formal_param)
        collection_entity["mainEntity"] = collection_formal_param
        return collection_entity

    def _get_collection_additional_type(self, collection_type: str | None) -> str:
        if collection_type and "paired" in collection_type:
            return "https://training.galaxyproject.org/training-material/faqs/galaxy/collections_build_list_paired.html"
        return "https://training.galaxyproject.org/training-material/faqs/galaxy/collections_build_list.html"

    def _get_parameter_additional_type(self, parameter_type: str | None) -> str:
        return ro_crate_parameter_type(parameter_type)

    def _add_collections(self, crate: ROCrate):
        # Process all invocations (parent + subworkflows)
        for invocation in self.model_store.included_invocations:
            # Only add formal parameters for the main invocation
            workflow_entity = self.workflow_definitions[invocation.workflow_id]
            action = self.invocation_actions[invocation.id]

            for wfdca in invocation.input_dataset_collections:
                if wfdca.dataset_collection:
                    collection_formal_param = self._add_collection_formal_parameter(
                        wfdca.dataset_collection,
                        crate,
                        f"#workflow-definition-{invocation.workflow_id}-collection-input-{wfdca.workflow_step_id}",
                        wfdca.workflow_step.label,
                    )
                    collection_entity = self._add_collection(wfdca.dataset_collection, crate, collection_formal_param)
                    workflow_entity.append_to("input", collection_formal_param)
                    action.append_to("object", collection_entity)

            for wfdca in invocation.output_dataset_collections:
                if wfdca.dataset_collection:
                    collection_formal_param = self._add_collection_formal_parameter(
                        wfdca.dataset_collection,
                        crate,
                        f"#workflow-definition-{invocation.workflow_id}-collection-output-{wfdca.workflow_output.id}",
                        wfdca.workflow_output.label or wfdca.workflow_output.output_name,
                    )
                    collection_entity = self._add_collection(wfdca.dataset_collection, crate, collection_formal_param)
                    workflow_entity.append_to("output", collection_formal_param)
                    action.append_to("result", collection_entity)

    def _add_workflows(self, crate: ROCrate):
        workflows_directory = self.model_store.workflows_directory

        if os.path.exists(workflows_directory):
            cwl_wf = None
            main_key = self.model_store.serialization_options.get_identifier(self.model_store.security, self.workflow)
            workflow_models = {}

            def register_workflow(workflow):
                key = self.model_store.serialization_options.get_identifier(self.model_store.security, workflow)
                workflow_models[key] = workflow
                for step in workflow.steps:
                    if step.subworkflow is not None:
                        register_workflow(step.subworkflow)

            register_workflow(self.workflow)
            for filename in sorted(os.listdir(workflows_directory)):
                is_main_wf = filename == f"{main_key}.gxwf.yml"
                is_computational_wf = not filename.endswith(".cwl")
                workflow_cls = ComputationalWorkflow if is_computational_wf else WorkflowDescription
                lang = "galaxy" if not filename.endswith(".cwl") else "cwl"
                dest_path = os.path.join("workflows", filename)

                wf = crate.add_workflow(
                    source=os.path.join(workflows_directory, filename),
                    dest_path=dest_path,
                    main=is_main_wf,
                    cls=workflow_cls,
                    lang=lang,
                )
                wf["encodingFormat"] = "application/yaml"
                workflow_key = filename.split(".", 1)[0]
                workflow_model = workflow_models.get(workflow_key)
                if workflow_model is not None and workflow_model.stored_workflow:
                    wf["version"] = str(workflow_model.version)
                self.workflow_entities[wf.id] = wf
                if lang == "cwl" and filename == f"{main_key}.abstract.cwl":
                    cwl_wf = wf

            if self.workflow.license:
                crate.mainEntity["license"] = self.workflow.license
            crate.mainEntity["name"] = self.workflow.name
            main_entity_types = crate.mainEntity._jsonld["@type"]
            if not isinstance(main_entity_types, list):
                main_entity_types = [main_entity_types]
            if "HowTo" not in main_entity_types:
                main_entity_types.append("HowTo")
            crate.mainEntity._jsonld["@type"] = main_entity_types
            crate.mainEntity["identifier"] = f"urn:uuid:{self.workflow.uuid}"
            if self.workflow.stored_workflow:
                crate.mainEntity["version"] = str(self.workflow.version)
            bioschemas_profile = crate.add(
                ContextEntity(
                    crate,
                    "https://bioschemas.org/profiles/ComputationalWorkflow/1.0-RELEASE",
                    properties={
                        "@type": "CreativeWork",
                        "name": "Bioschemas ComputationalWorkflow profile",
                        "version": "1.0-RELEASE",
                    },
                )
            )
            crate.mainEntity.append_to("conformsTo", bioschemas_profile)
            for key, value in self.model_store._date_properties(
                dateCreated=self.workflow.create_time, dateModified=self.workflow.update_time
            ).items():
                crate.mainEntity[key] = value
            workflow_description = self.workflow.readme or self.workflow.help
            if workflow_description and self.model_store._safe_metadata_value(workflow_description):
                crate.mainEntity["description"] = workflow_description
            if self.workflow.doi:
                crate.mainEntity["citation"] = [
                    {"@id": doi if doi.startswith("http") else f"https://doi.org/{doi}"}
                    for doi in self.workflow.doi
                    if self.model_store._safe_metadata_value(doi)
                ]
            if self.workflow.logo_url and self.model_store._safe_metadata_value(self.workflow.logo_url):
                crate.mainEntity["image"] = {"@id": self.workflow.logo_url}
            if self.workflow.source_metadata:
                source_url = self.workflow.source_metadata.get("trs_url") or self.workflow.source_metadata.get("url")
                if (
                    source_url
                    and source_url.startswith(("http://", "https://"))
                    and self.model_store._safe_metadata_value(source_url)
                ):
                    crate.mainEntity["isBasedOn"] = {"@id": source_url}
            workflow_path = os.path.join(self.model_store.export_directory, crate.mainEntity.id)
            if os.path.isfile(workflow_path):
                digest = hashlib.sha256()
                with open(workflow_path, "rb") as workflow_source:
                    for chunk in iter(lambda: workflow_source.read(1024 * 1024), b""):
                        digest.update(chunk)
                checksum_value = digest.hexdigest()
                checksum = crate.add(
                    ContextEntity(
                        crate,
                        f"#checksum-{checksum_value}",
                        properties={
                            "@type": "PropertyValue",
                            "name": "SHA-256",
                            "propertyID": "https://spdx.org/rdf/terms#checksumValue",
                            "value": checksum_value,
                        },
                    )
                )
                crate.mainEntity.append_to("additionalProperty", checksum)
            if cwl_wf:
                crate.mainEntity["subjectOf"] = cwl_wf

            # Adding multiple creators if available
            if self.workflow.creator_metadata:
                for creator_index, creator_data in enumerate(self.workflow.creator_metadata, start=1):
                    creator_data = {
                        key: value
                        for key, value in creator_data.items()
                        if key in {"class", "name", "identifier", "url"}
                        and self.model_store._safe_metadata_value(value)
                    }
                    if creator_data.get("class") == "Person":
                        creator_identifier = creator_data.get("identifier")
                        if creator_identifier and re.fullmatch(r"\d{4}-\d{4}-\d{4}-[\dX]{4}", creator_identifier):
                            creator_id = f"https://orcid.org/{creator_identifier}"
                        else:
                            creator_id = creator_identifier or f"#workflow-creator-{creator_index}"
                        # Create the person entity
                        creator_entity = crate.add(
                            ContextEntity(
                                crate,
                                creator_id,
                                properties={
                                    "@type": "Person",
                                    "name": creator_data.get("name") or "Unknown creator",
                                    **({"identifier": creator_identifier} if creator_identifier else {}),
                                    **({"url": creator_data["url"]} if creator_data.get("url") else {}),
                                },
                            )
                        )
                        # Append the person creator entity to the mainEntity
                        crate.mainEntity.append_to("creator", creator_entity)

                    elif creator_data.get("class") == "Organization":
                        organization_url = creator_data.get("url")
                        # Create the organization entity
                        organization_entity = crate.add(
                            ContextEntity(
                                crate,
                                organization_url or f"#workflow-creator-{creator_index}",
                                properties={
                                    "@type": "Organization",
                                    "name": creator_data.get("name") or "Unknown organization",
                                    **({"url": organization_url} if organization_url else {}),
                                },
                            )
                        )
                        # Append the organization entity to the mainEntity
                        crate.mainEntity.append_to("creator", organization_entity)

        self.workflow_definitions[self.workflow.id] = crate.mainEntity
        self._register_subworkflows(self.workflow, crate)
        # Add tools used in the workflow
        self._add_tools(crate)
        self._add_steps(crate)

        stored_workflow = self.workflow.stored_workflow
        if stored_workflow:
            keywords = [
                f"{tag.user_tname}:{tag.user_value}" if tag.user_value else tag.user_tname
                for tag in stored_workflow.tags
                if tag.user_tname
            ]
            if keywords:
                crate.mainEntity["keywords"] = keywords

    def _add_steps(self, crate: ROCrate):
        """
        Add workflow steps (HowToStep) to the RO-Crate. These are unique for each tool occurrence.
        """
        step_entities: list[ContextEntity] = []
        # Initialize the position as a list with a single element to keep it mutable
        position = [1]
        self._add_steps_recursive(self.workflow.steps, crate, step_entities, position)
        return step_entities

    def _register_subworkflows(self, workflow, crate):
        for step in workflow.steps:
            nested = step.subworkflow
            if nested is None or nested.id in self.workflow_definitions:
                continue
            properties = {
                "@type": ["ComputationalWorkflow", "SoftwareSourceCode", "HowTo"],
                "name": nested.name,
                "identifier": f"urn:uuid:{nested.uuid}",
                "programmingLanguage": crate.mainEntity["programmingLanguage"],
            }
            for name in ("license", "readme", "help"):
                value = getattr(nested, name, None)
                if value and self.model_store._safe_metadata_value(value):
                    properties["license" if name == "license" else "description"] = value
            key = self.model_store.serialization_options.get_identifier(self.model_store.security, nested)
            entity = crate.get(f"workflows/{key}.gxwf.yml")
            if entity is None:
                entity = crate.add(ContextEntity(crate, f"#workflow-definition-{nested.uuid}", properties=properties))
            else:
                properties["@type"] = ["File", *properties["@type"]]
                for name, value in properties.items():
                    if name == "@type":
                        entity.properties()[name] = value
                    else:
                        entity[name] = value
            for name, value in self.model_store._date_properties(
                dateCreated=nested.create_time, dateModified=nested.update_time
            ).items():
                entity[name] = value
            if nested.stored_workflow:
                entity["version"] = str(nested.version)
                entity["keywords"] = [
                    f"{tag.user_tname}:{tag.user_value}" if tag.user_value else tag.user_tname
                    for tag in nested.stored_workflow.tags
                    if tag.user_tname
                ]
            if nested.doi:
                entity["citation"] = [
                    {"@id": value if value.startswith("https://doi.org/") else f"https://doi.org/{value}"}
                    for value in nested.doi
                    if self.model_store._safe_metadata_value(value)
                ]
            alternative = crate.get(f"workflows/{key}.abstract.cwl")
            if alternative is not None:
                entity["subjectOf"] = alternative
            native_path = os.path.join(self.model_store.export_directory, entity.id)
            if os.path.isfile(native_path):
                with open(native_path, "rb") as source:
                    digest = hashlib.sha256()
                    for chunk in iter(lambda: source.read(1024 * 1024), b""):
                        digest.update(chunk)
                    checksum = digest.hexdigest()
                self.model_store._attach_dataset_checksum(crate, entity, {"_galaxy_sha256": checksum})
            for index, creator in enumerate(nested.creator_metadata or []):
                values = {
                    key: value
                    for key, value in creator.items()
                    if key in {"name", "givenName", "familyName", "identifier", "url"}
                    and self.model_store._safe_metadata_value(value)
                }
                values["@type"] = "Organization" if creator.get("class") == "Organization" else "Person"
                entity.append_to(
                    "creator",
                    crate.add(ContextEntity(crate, f"#nested-{nested.uuid}-creator-{index}", properties=values)),
                )
            self.workflow_definitions[nested.id] = entity
            self._register_subworkflows(nested, crate)

    def _add_steps_recursive(self, steps, crate: ROCrate, step_entities, position, parent=None):
        """
        Recursively add HowToStep entities from workflow steps, ensuring that
        the position index is maintained across subworkflows.
        """
        parent = parent or crate.mainEntity
        for step in steps:
            step_metadata = {
                "type": step.type,
                "label": step.label,
                "uuid": str(step.uuid) if step.uuid else None,
                "order_index": step.order_index,
            }
            if self.model_store._safe_metadata_value(step.when_expression):
                step_metadata["when"] = step.when_expression
            self.model_store._add_metadata_property(crate, parent, f"Galaxy step {step.order_index}", step_metadata)
            if step.type in {"tool", "subworkflow"}:
                # Create a unique HowToStep entity for each step
                step_id = f"#workflow-step-{step.id}"
                step_description = None
                if step.annotations:
                    annotations_list = [annotation.annotation for annotation in step.annotations if annotation]
                    step_description = " ".join(annotations_list) if annotations_list else None

                # Add HowToStep entity to the crate
                tool_key = (step.tool_id, step.tool_version)
                tool_entity = self.tool_cache.get(tool_key)
                if step.type == "subworkflow":
                    tool_entity = self.workflow_definitions.get(step.subworkflow_id)
                step_entity = crate.add(
                    ContextEntity(
                        crate,
                        step_id,
                        properties={
                            "@type": "HowToStep",
                            "position": position[0],
                            "name": step.label or step.tool_id or "Subworkflow",
                            "description": step_description,
                            "workExample": tool_entity,
                        },
                    )
                )

                # Append the HowToStep entity to the workflow steps list
                step_entities.append(step_entity)
                if step.id is not None:
                    self.step_cache[step.id] = step_entity
                parent.append_to("step", step_entity)
                if step.tags:
                    step_entity["keywords"] = [
                        f"{tag.user_tname}:{tag.user_value}" if tag.user_value else tag.user_tname
                        for tag in step.tags
                        if tag.user_tname
                    ]

                # Increment the position counter
                position[0] += 1

            # Handle subworkflows recursively
            if step.type == "subworkflow":
                subworkflow = step.subworkflow
                if subworkflow:
                    self._add_steps_recursive(
                        subworkflow.steps, crate, step_entities, [1], self.workflow_definitions[subworkflow.id]
                    )

    def _add_tools(self, crate: ROCrate):
        tool_entities: list[ContextEntity] = []
        self._add_tools_recursive(self.workflow.steps, crate, tool_entities)

    def _add_tools_recursive(self, steps, crate: ROCrate, tool_entities, parent=None):
        """
        Recursively add SoftwareApplication entities from workflow steps, reusing tools when necessary.
        """
        parent = parent or crate.mainEntity
        for step in steps:
            if step.type == "tool":
                tool_id = step.tool_id
                tool_version = step.tool_version

                # Cache key based on tool ID and version
                tool_key = (tool_id, tool_version)

                # Check if tool entity is already in cache
                if tool_key in self.tool_cache:
                    tool_entity = self.tool_cache[tool_key]
                else:
                    # Create a new tool entity
                    tool_name = tool_id
                    tool_description = None
                    if step.annotations:
                        annotations_list = [annotation.annotation for annotation in step.annotations if annotation]
                        tool_description = " ".join(annotations_list) if annotations_list else None

                    # Add tool entity to the RO-Crate
                    tool_entity = crate.add(
                        ContextEntity(
                            crate,
                            self.model_store._tool_entity_id(tool_id, tool_version),
                            properties={
                                "@type": "SoftwareApplication",
                                "name": tool_name,
                                **({"softwareVersion": tool_version} if tool_version else {}),
                                "description": tool_description,
                            },
                        )
                    )

                    self.model_store._enrich_tool_entity(crate, tool_entity, tool_id, tool_version)
                    # Store the tool entity in the cache
                    self.tool_cache[tool_key] = tool_entity

                # Append the tool entity to the workflow (instrument) and store it in the list
                self.model_store._add_dynamic_tool_metadata(crate, tool_entity, step.dynamic_tool)
                tool_entities.append(tool_entity)
                parent.append_to("hasPart", tool_entity)

            # Handle subworkflows recursively
            elif step.type == "subworkflow":
                subworkflow = step.subworkflow
                if subworkflow:
                    nested = self.workflow_definitions[subworkflow.id]
                    parent.append_to("hasPart", nested)
                    self._add_tools_recursive(subworkflow.steps, crate, tool_entities, nested)

    def _add_step_execution_provenance(self, crate: ROCrate, job_actions: dict[int, ContextEntity]) -> set[int]:
        controlled_steps = set()
        for job_id, job_action in job_actions.items():
            job = self.model_store.included_jobs[job_id]
            invocation_step = job.effective_workflow_invocation_step
            if not invocation_step or not invocation_step.workflow_step:
                continue
            workflow_step = invocation_step.workflow_step
            how_to_step = self.step_cache.get(workflow_step.id)
            if not how_to_step:
                continue
            control_action = crate.add(
                ContextEntity(
                    crate,
                    f"#workflow-step-execution-{invocation_step.id}-job-{job_id}",
                    properties={
                        "@type": "ControlAction",
                        "name": f"Execution of workflow step {workflow_step.label or workflow_step.order_index}",
                        "description": "Galaxy execution of a workflow step.",
                        "instrument": how_to_step,
                        "object": job_action,
                        **({"actionStatus": job_action["actionStatus"]} if job_action.get("actionStatus") else {}),
                        **({"startTime": job_action["startTime"]} if job_action.get("startTime") else {}),
                        **({"endTime": job_action["endTime"]} if job_action.get("endTime") else {}),
                    },
                )
            )
            self.engine_actions[invocation_step.workflow_invocation_id].append_to("object", control_action)
            crate.root_dataset.append_to("mentions", control_action)
            controlled_steps.add(invocation_step.id)
        for invocation in self.model_store.included_invocations:
            for association in invocation.subworkflow_invocations:
                nested_action = self.invocation_actions.get(association.subworkflow_invocation_id)
                step_entity = self.step_cache.get(association.workflow_step_id)
                if nested_action is None or step_entity is None:
                    continue
                control = crate.add(
                    ContextEntity(
                        crate,
                        f"#nested-workflow-control-{association.id}",
                        properties={
                            "@type": "ControlAction",
                            "name": "Subworkflow execution",
                            "description": "Galaxy execution of a nested workflow.",
                            "instrument": step_entity,
                            "object": nested_action,
                            **(
                                {"actionStatus": nested_action["actionStatus"]}
                                if nested_action.get("actionStatus")
                                else {}
                            ),
                        },
                    )
                )
                self.engine_actions[invocation.id].append_to("object", control)
                for step in invocation.steps:
                    if step.workflow_step_id == association.workflow_step_id:
                        controlled_steps.add(step.id)
        return controlled_steps

    def _add_create_action(self, crate: ROCrate):
        action_id = (
            f"urn:uuid:{self.invocation.uuid}" if self.invocation.uuid else f"#workflow-run-{self.invocation.id}"
        )
        job_state_summary = self.invocation.compute_recursive_job_state_summary()
        failed = any(job_state_summary.get(state, 0) for state in ("error", "failed", "deleted"))
        active = any(
            count
            for state, count in job_state_summary.items()
            if state not in {"ok", "skipped", "error", "failed", "deleted"}
        )
        if failed or self.invocation.state in {"cancelled", "cancelling", "failed"}:
            action_status = "http://schema.org/FailedActionStatus"
        elif self.invocation.completion and not active:
            action_status = "http://schema.org/CompletedActionStatus"
        elif active or self.invocation.state != "scheduled" or not job_state_summary:
            action_status = None
        else:
            action_status = "http://schema.org/CompletedActionStatus"
        self.create_action = crate.add(
            ContextEntity(
                crate,
                action_id,
                properties={
                    "@type": "CreateAction",
                    "name": self.workflow.name,
                    "description": f'Galaxy workflow invocation of "{self.workflow.name}".',
                    **self.model_store._date_properties(startTime=self.invocation.create_time),
                    **({"actionStatus": action_status} if action_status else {}),
                    "instrument": self.workflow_definitions.get(self.workflow.id, crate.mainEntity),
                },
            )
        )
        errors = [
            job.info
            for job in self._invocation_jobs(self.invocation)
            if job.state in {"error", "failed", "deleted"}
            and job.info
            and self.model_store._safe_metadata_value(job.info)
        ]
        if errors:
            self.create_action["error"] = "; ".join(dict.fromkeys(errors))
        completion = self.invocation.completion
        if completion:
            if completion.completion_time:
                for name, value in self.model_store._date_properties(endTime=completion.completion_time).items():
                    self.create_action[name] = value
            self.model_store._add_metadata_property(
                crate, self.create_action, "Galaxy completion job state summary", completion.job_state_summary
            )
        self.model_store._add_metadata_property(
            crate, self.create_action, "Galaxy invocation state", self.invocation.state
        )
        reasons = [message.reason for message in self.invocation.messages if message.reason]
        self.model_store._add_metadata_property(crate, self.create_action, "Galaxy invocation message reasons", reasons)
        user = getattr(self.invocation, "user", None) or (self.invocation.history and self.invocation.history.user)
        if user:
            agent = self.model_store._add_user_entity(crate, user)
            self.create_action["agent"] = agent
        crate.root_dataset.append_to("mentions", self.create_action)

    @staticmethod
    def _invocation_jobs(invocation):
        jobs = {job.id: job for step in invocation.steps for job in step.jobs}
        for association in invocation.subworkflow_invocations:
            for job in WorkflowRunCrateProfileBuilder._invocation_jobs(association.subworkflow_invocation):
                jobs[job.id] = job
        return list(jobs.values())

    def _add_engine_run(self, crate: ROCrate):
        jobs = self._invocation_jobs(self.invocation)
        versions = sorted({job.galaxy_version for job in jobs if job.galaxy_version})
        single_known_version = len(versions) == 1 and all(job.galaxy_version for job in jobs)
        roc_engine = crate.add(
            SoftwareApplication(
                crate,
                identifier=f"urn:galaxy:workflow-engine:{self.invocation.uuid or self.invocation.id}",
                properties={
                    "name": "Galaxy workflow engine",
                    **({"softwareVersion": versions[0]} if single_known_version else {}),
                    "url": "https://galaxyproject.org/",
                },
            )
        )
        self.model_store._add_metadata_property(crate, roc_engine, "Recorded Galaxy execution versions", versions)
        if not single_known_version:
            self.model_store._add_metadata_property(
                crate,
                roc_engine,
                "Execution version availability",
                "No single execution version is recorded; the export generator version is recorded separately.",
            )
        roc_engine_run = crate.add(
            ContextEntity(
                crate,
                f"#workflow-engine-run-{self.invocation.id}",
                properties={
                    "@type": "OrganizeAction",
                    "name": f"Run of {roc_engine['name']}",
                    "description": "Galaxy workflow-engine orchestration for this invocation.",
                    **self.model_store._date_properties(startTime=self.invocation.create_time),
                    **({"endTime": self.create_action["endTime"]} if self.create_action.get("endTime") else {}),
                },
            )
        )
        roc_engine_run["instrument"] = roc_engine
        roc_engine_run["result"] = self.create_action
        crate.root_dataset.append_to("mentions", roc_engine_run)
        self.roc_engine_run = roc_engine_run

    def _add_readme(self, crate: ROCrate):
        readme_path = os.path.join(self.model_store.export_directory, "README.md")
        with open(readme_path, "w") as readme:
            readme.write(self.model_store._generate_markdown_readme())
        crate.add_file(
            readme_path,
            dest_path="README.md",
            properties={
                "name": "README.md",
                "encodingFormat": "text/markdown",
                "about": {"@id": "./"},
            },
        )

    def _add_profiles(self, crate: ROCrate):
        profiles = []
        for p in "process", "workflow":
            id_ = f"https://w3id.org/ro/wfrun/{p}/{PROFILES_VERSION}"
            profiles.append(
                crate.add(
                    ContextEntity(
                        crate,
                        id_,
                        properties={
                            "@type": "CreativeWork",
                            "name": f"{p.title()} Run Crate",
                            "version": PROFILES_VERSION,
                        },
                    )
                )
            )
        # FIXME: in the future, this could go out of sync with the wroc
        # profile added by ro-crate-py to the metadata descriptor
        wroc_profile_id = f"https://w3id.org/workflowhub/workflow-ro-crate/{WROC_PROFILE_VERSION}"
        profiles.append(
            crate.add(
                ContextEntity(
                    crate,
                    wroc_profile_id,
                    properties={
                        "@type": "CreativeWork",
                        "name": "Workflow RO-Crate",
                        "version": WROC_PROFILE_VERSION,
                    },
                )
            )
        )
        if self.provenance_complete:
            profiles.append(
                crate.add(
                    ContextEntity(
                        crate,
                        f"https://w3id.org/ro/wfrun/provenance/{PROFILES_VERSION}",
                        properties={
                            "@type": "CreativeWork",
                            "name": "Provenance Run Crate",
                            "version": PROFILES_VERSION,
                        },
                    )
                )
            )
        crate.root_dataset["conformsTo"] = profiles

    def _add_parameters(self, crate: ROCrate):
        workflow_entity = getattr(self, "workflow_definitions", {}).get(
            getattr(self.invocation, "workflow_id", None), crate.mainEntity
        )
        for step in self.invocation.steps:
            if step.workflow_step.type == "parameter_input":
                property_value = self._add_step_parameter(step, crate)
                self.create_action.append_to("object", property_value)
        for output in self.invocation.output_values:
            name = output.workflow_output.label or output.workflow_output.output_name
            identifier = f"#workflow-{self.invocation.id}-scalar-output-{output.workflow_output.id}"
            parameter_type = {
                bool: "Boolean",
                int: "Integer",
                float: "Float",
                str: "Text",
                list: "Collection",
                dict: "Collection",
            }.get(type(output.value), "Text")
            parameter = crate.add(
                ContextEntity(
                    crate,
                    f"#workflow-definition-{getattr(self.invocation, 'workflow_id', self.invocation.id)}-scalar-output-{output.workflow_output.id}-parameter",
                    properties={"@type": "FormalParameter", "name": name, "additionalType": parameter_type},
                )
            )
            value = self._parameter_value(crate, identifier, name, output.value, parameter)
            workflow_entity.append_to("output", parameter)
            self.create_action.append_to("result", value)

    def _parameter_value(self, crate, identifier, name, value, parameter=None):
        properties = {"@type": "PropertyValue", "name": name or "Unnamed parameter"}
        if parameter is not None:
            properties["exampleOfWork"] = parameter
        if not self.model_store._safe_metadata_value(value):
            properties["description"] = "Value withheld by export privacy policy."
        elif value is None:
            properties["description"] = "No value was recorded."
        elif isinstance(value, str):
            properties["description"] = "Text value withheld because workflow parameters can contain credentials."
        elif isinstance(value, (list, dict)):
            properties["@type"] = "Collection"
            properties["additionalType"] = (
                "https://galaxyproject.org/parameter/record"
                if isinstance(value, dict)
                else "https://galaxyproject.org/parameter/list"
            )
            members, items = [], []
            for index, (label, item) in enumerate(value.items() if isinstance(value, dict) else enumerate(value)):
                member = self._parameter_value(crate, f"{identifier}-value-{index}", str(label), item)
                members.append(member)
                items.append(
                    crate.add(
                        ContextEntity(
                            crate,
                            f"{identifier}-item-{index}",
                            properties={"@type": "ListItem", "name": str(label), "position": index + 1, "item": member},
                        )
                    )
                )
            properties.update(hasPart=members, itemListElement=items, numberOfItems=len(members))
        else:
            properties["value"] = value
        return crate.add(ContextEntity(crate, identifier, properties=properties))

    def _add_step_parameter(self, step: WorkflowInvocationStep, crate: ROCrate) -> ContextEntity:
        param_id = step.workflow_step.label
        assert step.workflow_step.tool_inputs
        param_type = step.workflow_step.tool_inputs["parameter_type"]
        formal_param = crate.add(
            ContextEntity(
                crate,
                f"#workflow-definition-{self.invocation.workflow_id}-parameter-{step.workflow_step.id}",
                properties={
                    "@type": "FormalParameter",
                    "additionalType": self._get_parameter_additional_type(param_type),
                    "description": self._get_association_description(step.workflow_step),
                    "name": f"{param_id}",
                    "valueRequired": not step.workflow_step.input_optional,
                },
            )
        )
        workflow_entity = self.workflow_definitions.get(self.invocation.workflow_id, crate.mainEntity)
        workflow_entity.append_to("input", formal_param)
        tool_inputs = step.workflow_step.tool_inputs
        for name in ("default", "min", "max", "options"):
            value = tool_inputs.get(name)
            if is_publishable_metadata_field(param_id, value):
                self.model_store._add_metadata_property(crate, formal_param, f"Galaxy parameter {name}", value)

        # Handle case where output_value is None (e.g., optional parameter not provided)
        output_value = None
        if step.output_value:
            output_value = step.output_value.value
        else:
            for parameter in self.invocation.input_step_parameters:
                if parameter.workflow_step_id == step.workflow_step.id:
                    output_value = parameter.parameter_value
                    break
        return self._parameter_value(
            crate,
            f"#workflow-{self.invocation.id}-parameter-value-{step.workflow_step.id}",
            param_id,
            output_value,
            formal_param,
        )

    def _add_step_tool_fp(self, step: WorkflowInvocationStep, tool_input: str, crate: ROCrate):
        param_id = tool_input
        param_type = "text"
        return ContextEntity(
            crate,
            f"{param_id}-param",
            properties={
                "@type": "FormalParameter",
                "additionalType": self._get_parameter_additional_type(param_type),
                "description": self._get_association_description(step.workflow_step),
                "name": f"{step.workflow_step.label}",
                "valueRequired": not step.workflow_step.input_optional,
            },
        )

    def _add_dataset_formal_parameter(self, hda: HistoryDatasetAssociation, crate: ROCrate, identifier=None, name=None):
        assert hda.dataset is not None
        filename, _ = self.model_store.dataset_id_to_path.get(hda.dataset.id, (None, None))
        return crate.add(
            ContextEntity(
                crate,
                identifier or str(hda.dataset.uuid),
                properties={
                    "@type": "FormalParameter",
                    "additionalType": "File" if filename else "Dataset",
                    "description": self._get_association_description(hda),
                    "name": name or hda.name,
                },
            )
        )

    def _add_collection_formal_parameter(
        self, hdca: HistoryDatasetCollectionAssociation, crate: ROCrate, identifier=None, name=None
    ) -> ContextEntity:
        return crate.add(
            ContextEntity(
                crate,
                identifier or f"{hdca.type_id}-param",
                properties={
                    "@type": "FormalParameter",
                    "additionalType": "Collection",
                    "description": self._get_association_description(hdca),
                    "name": name or hdca.name,
                },
            )
        )

    def _get_association_description(self, association: Any) -> str:
        if hasattr(association, "annotations"):
            return association.annotations[0].annotation if association.annotations else ""
        elif hasattr(association, "info"):
            return association.info
        return ""
