sequenceDiagram
    participant Browser
    participant Server
    Note over Browser,Server: HTTP
    Browser->>+Server: Page Request
    Server->>-Browser: Static Content (HTML+JS+CSS)
    Note left of Browser: Render HTML fragraments with JavaScript
