/**
 * Contains build in activities
 */

export const Activities = [
    {
        description: "Opens a data dialog, allowing uploads from URL or disk.",
        icon: "upload",
        id: "upload",
        mutable: false,
        optional: false,
        title: "Upload",
        to: null,
        tooltip: "Download from URL or upload files from disk",
        visible: true,
    },
    {
        description: "Displays the tool panel to search and access all available tools.",
        icon: "wrench",
        id: "tools",
        mutable: false,
        optional: false,
        title: "Tools",
        to: null,
        tooltip: "Search and run tools",
        visible: true,
    },
    {
        description: "Displays the workflow panel to search and access all available workflows.",
        icon: "sitemap",
        id: "workflow",
        mutable: false,
        optional: false,
        title: "Workflow",
        to: null,
        tooltip: "Download from URL or upload files from disk",
        visible: true,
    },
    {
        description: "Shows to the list of available visualizations.",
        icon: "chart-bar",
        id: "visualizations",
        mutable: false,
        optional: true,
        title: "Visualize",
        to: "/visualizations",
        tooltip: "Visualize datasets",
        visible: true,
    },
    {
        description: "Shows all of your histories in the center panel.",
        icon: "fa-hdd",
        id: "histories",
        mutable: false,
        optional: true,
        title: "Histories",
        tooltip: "Show all histories",
        to: "/histories/list",
        visible: true,
    },
    {
        description: "Displays all of your datasets across all histories in the center panel.",
        icon: "fa-folder",
        id: "datasets",
        mutable: false,
        optional: true,
        title: "Datasets",
        tooltip: "Show all datasets",
        to: "/datasets/list",
        visible: false,
    },
    {
        description: "Displays all workflow invocations.",
        icon: "fa-list",
        id: "invocation",
        mutable: false,
        optional: true,
        title: "Invocations",
        tooltip: "Show all invocations",
        to: "/workflows/invocations",
        visible: false,
    },
];

export default Activities;
