#! /usr/bin/perl -w

use strict;
use warnings;

# Unpacks name field generated by Text2BedLike.pl
# BedLike2Text.pl [input BedLike file] [output file]

my $bedLike = 0;
my $command = "cut -f 4 $ARGV[0] | sed s/^BedLike\\|// | tr \" \" \"\t\" > $ARGV[1]";
die "Not enough arguments" unless @ARGV == 2;

# Check that the file is BedLike:

open (TEST, "head -n 2 $ARGV[0] |") or die "Cannot run head:$!\n";
while (<TEST>) {
    $bedLike = 1 if ([split "\|"]->[3] =~ /^BedLike/);
}
close TEST;

if ($bedLike == 1) {
    system($command);
} else {
    die "<font color=\"yellow\">Not a BedLike file.  Check you query choice</font>\n";
}
    
