/**
 * List of built-in activities
 */
import {
    faChartBar,
    faColumns,
    faDatabase,
    faFile,
    faFileContract,
    faFolder,
    faHdd,
    faLaptop,
    faList,
    faPlay,
    faSitemap,
    faUpload,
    faWrench,
} from "@fortawesome/free-solid-svg-icons";

import { type Activity } from "@/stores/activityStore";
import { type EventData } from "@/stores/eventStore";

export const defaultActivities = [
    {
        anonymous: false,
        description: "显示当前运行的交互式工具(ITs)，如果管理员启用了这些功能。",
        icon: faLaptop,
        id: "interactivetools",
        mutable: false,
        optional: false,
        panel: false,
        title: "交互式工具",
        tooltip: "显示活动的交互式工具",
        to: "/interactivetool_entry_points/list",
        visible: true,
    },
    {
        anonymous: true,
        description: "打开数据对话框，允许从URL、粘贴内容或磁盘上传。",
        icon: faUpload,
        id: "upload",
        mutable: false,
        optional: false,
        panel: false,
        title: "上传",
        to: null,
        tooltip: "从URL下载或从磁盘上传文件",
        visible: true,
    },
    {
        anonymous: true,
        description: "显示工具面板以搜索和访问所有可用工具。",
        icon: faWrench,
        id: "tools",
        mutable: false,
        optional: false,
        panel: true,
        title: "工具",
        to: null,
        tooltip: "搜索并运行工具",
        visible: true,
    },
    {
        anonymous: true,
        description: "显示用于搜索和访问工作流的面板。",
        icon: faSitemap,
        id: "workflows",
        mutable: false,
        optional: true,
        panel: false,
        title: "工作流",
        to: "/workflows/list",
        tooltip: "搜索并运行工作流",
        visible: true,
    },
    {
        anonymous: false,
        description: "显示所有工作流运行。",
        icon: faList,
        id: "invocation",
        mutable: false,
        optional: true,
        panel: true,
        title: "工作流调用",
        tooltip: "显示所有工作流运行",
        to: null,
        visible: true,
    },
    {
        anonymous: true,
        description: "显示可用可视化列表。",
        icon: faChartBar,
        id: "visualizations",
        mutable: false,
        optional: true,
        panel: true,
        title: "可视化",
        to: null,
        tooltip: "可视化数据集",
        visible: true,
    },
    {
        anonymous: true,
        description: "显示所有历史记录列表。",
        icon: faHdd,
        id: "histories",
        mutable: false,
        optional: true,
        panel: false,
        title: "历史记录",
        tooltip: "显示所有历史记录",
        to: "/histories/list",
        visible: true,
    },
    {
        anonymous: false,
        description: "显示历史选择器面板并在中心面板中打开历史多视图。",
        icon: faColumns,
        id: "multiview",
        mutable: false,
        optional: true,
        panel: true,
        title: "历史多视图",
        tooltip: "选择要在历史多视图中显示的历史记录",
        to: "/histories/view_multiple",
        visible: true,
    },
    {
        anonymous: false,
        description: "显示所有历史记录中的所有数据集。",
        icon: faFolder,
        id: "datasets",
        mutable: false,
        optional: true,
        panel: false,
        title: "数据集",
        tooltip: "显示所有数据集",
        to: "/datasets/list",
        visible: true,
    },
    {
        anonymous: true,
        description: "显示并创建新页面。",
        icon: faFileContract,
        id: "pages",
        mutable: false,
        optional: true,
        panel: false,
        title: "页面",
        tooltip: "显示所有页面",
        to: "/pages/list",
        visible: true,
    },
    {
        anonymous: false,
        description: "显示包含所有用户可用数据集的数据库。",
        icon: faDatabase,
        id: "libraries",
        mutable: false,
        optional: true,
        panel: false,
        title: "数据库",
        tooltip: "访问数据库",
        to: "/libraries",
        visible: true,
    },
] as const;

export function convertDropData(data: EventData): Activity | null {
    if (data.history_content_type === "dataset") {
        return {
            anonymous: true,
            description: "显示此数据集。",
            icon: faFile,
            id: `dataset-${data.id}`,
            mutable: true,
            optional: true,
            panel: false,
            title: data.name as string,
            tooltip: "查看您的数据集",
            to: `/datasets/${data.id}/preview`,
            visible: true,
        };
    }
    if (data.model_class === "StoredWorkflow") {
        return {
            anonymous: false,
            description: data.description as string,
            icon: faPlay,
            id: `workflow-${data.id}`,
            mutable: true,
            optional: true,
            panel: false,
            title: data.name as string,
            tooltip: data.name as string,
            to: `/workflows/run?id=${data.id}`,
            visible: true,
        };
    }
    return null;
}
