/**
 * Requests jobs
 * Requests response generated by a tool run
 */

import { defineStore } from "pinia";
import { ref } from "vue";

import { GalaxyApi } from "@/api";
import { type ResponseVal, type ShowFullJobResponse, TERMINAL_STATES } from "@/api/jobs";
import { type FetchParams, useKeyedCache } from "@/composables/keyedCache";
import { useResourceWatcher } from "@/composables/resourceWatcher";
import { rethrowSimpleWithStatus } from "@/utils/simple-error";

interface JobFetchParams extends FetchParams {
    /** Whether to request the full job representation. Defaults to `true`. */
    full?: boolean;
}

export const useJobStore = defineStore("jobStore", () => {
    const latestResponse = ref<ResponseVal | null>(null);

    async function fetchJobById(params: JobFetchParams): Promise<ShowFullJobResponse> {
        const { data, error, response } = await GalaxyApi().GET("/api/jobs/{job_id}", {
            params: { path: { job_id: params.id }, query: { full: params.full ?? true } },
        });
        if (error) {
            rethrowSimpleWithStatus(error, response);
        }
        return data;
    }

    function saveLatestResponse(newResponse: ResponseVal) {
        latestResponse.value = newResponse;
    }

    const {
        storedItems: storedJobs,
        fetchItemById: fetchJobKeyedCache,
        getItemById: getJob,
        getItemLoadError: getJobLoadError,
        isLoadingItem: isLoadingJob,
    } = useKeyedCache<ShowFullJobResponse>(fetchJobById);

    /** An overloaded fetch function that ensures the job is retrieved from the keyed cache,
     * but with the additional, optional `full` option for requesting the full job representation.
     */
    async function fetchJob(params: JobFetchParams) {
        return fetchJobKeyedCache(params as FetchParams);
    }

    /** Tracks job ids for which the full representation has been loaded. */
    const fullyLoadedJobIds = new Set<string>();

    /** A track of all active polls (by `job_id` and whether the stored representation is full),
     * plus a count of how many callers still want that poll running, so we don't duplicate polls
     * for the same ID and stop polling once the last interested caller goes away. */
    const activePolls = new Map<
        string,
        { watcher: ReturnType<typeof useResourceWatcher>; full: boolean; refCount: number }
    >();

    /**
     * Polls a job until it reaches a terminal state. If the job is already terminal and cached,
     * it may not poll at all. If the stored job is not a full representation and a full one is
     * requested, it will fetch the full representation once *or* switch an ongoing poll to request
     * the full representation if needed.
     *
     * Returns a `stopWatchingJob` function the caller must invoke (e.g. from `onUnmounted`) once it
     * no longer needs this job polled because the underlying poll only actually stops once every caller
     * that started it has done so.
     */
    function pollJobUntilTerminal(params: JobFetchParams): { stopWatchingJob: () => void } {
        const { id, full = true } = params;
        const stopWatchingReturn = { stopWatchingJob: () => {} };

        // Not using `getJob` here because that would trigger a fetch if the job isn't already cached
        const cachedJob = storedJobs.value[id];
        const cachedJobIsTerminal = !!cachedJob && TERMINAL_STATES.indexOf(cachedJob.state) !== -1;

        /** Whether the cached job satisfies the current request, considering the `full` option. */
        const cacheSatisfiesRequest = full ? fullyLoadedJobIds.has(id) : !!cachedJob;
        if (cachedJobIsTerminal && cacheSatisfiesRequest) {
            // Already have everything this call needs, and the job won't change anymore.
            return stopWatchingReturn;
        }

        // The cached job is terminal but doesn't satisfy the currently requested structure
        if (cachedJobIsTerminal) {
            fetchJob({ id, full: true }).then((job) => {
                if (job) {
                    fullyLoadedJobIds.add(id);
                }
            });
            return stopWatchingReturn;
        }

        const runningPoll = activePolls.get(id);
        if (runningPoll !== undefined) {
            runningPoll.refCount++;
            // We need to switch an ongoing non-`full` poll to request `full`.
            if (full && !runningPoll.full) {
                runningPoll.full = true;
            }
            return { stopWatchingJob: () => stopWatchingJob(id) };
        }

        const watcher = useResourceWatcher(
            async () => {
                // Read (not close over) the current requested level as a later call may have
                // upgraded this poll to `full: true` since it started.
                const requestFull = activePolls.get(id)?.full ?? full;
                const job = await fetchJob({ id, full: requestFull });
                if (job && requestFull) {
                    fullyLoadedJobIds.add(id);
                }
                if (job && TERMINAL_STATES.indexOf(job.state) !== -1) {
                    watcher.stopWatchingResource();
                    activePolls.delete(id);
                }
            },
            { shortPollingInterval: 1000, longPollingInterval: 1000 },
        );
        activePolls.set(id, { watcher, full, refCount: 1 });
        watcher.startWatchingResource();
        return { stopWatchingJob: () => stopWatchingJob(id) };
    }

    /** Marks one caller as no longer interested in a job's poll; the poll itself only stops once
     * every caller that started it has done the same (see `pollJobUntilTerminal`'s `refCount`). */
    function stopWatchingJob(id: string) {
        const runningPoll = activePolls.get(id);
        if (!runningPoll) {
            return;
        }
        runningPoll.refCount--;
        if (runningPoll.refCount <= 0) {
            runningPoll.watcher.stopWatchingResource();
            activePolls.delete(id);
        }
    }

    return {
        fetchJob,
        saveLatestResponse,
        getJob,
        getJobLoadError,
        isLoadingJob,
        latestResponse,
        pollJobUntilTerminal,
    };
});
