<template>
    <div id="right" class="unified-panel">
        <div class="unified-panel-header" unselectable="on">
            <div class="unified-panel-header-inner">
                <div class="panel-header-text">Details</div>
            </div>
        </div>
        <div class="unified-panel-body workflow-right">
            <div id="edit-attributes" class="right-content p-2">
                <div id="workflow-name-area">
                    <b>Name</b>
                    <b-input id="workflow-name" :value="workflow.name" @change="onRename"/>
                </div>
                <div id="workflow-version-area" class="mt-2">
                    <b>Version</b>
                    <select id="workflow-version-switch" class="ui-input"
                        >Select version</select
                    >
                </div>
                <div id="workflow-annotation-area" class="mt-2">
                    <b>Annotation</b>
                    <b-textarea id="workflow-annotation" :value="workflow.annotation" />
                    <div class="form-text text-muted">
                        These notes will be visible when this workflow is viewed.
                    </div>
                </div>
                <div class="mt-2">
                    <b>Tags</b>
                    <Tags :item="workflow" @input="onTags" />
                    <div class="form-text text-muted">
                        Apply tags to make it easy to search for and find items with the same tag.
                    </div>
                </div>
                <div class="mt-2">
                    <b>Outputs</b>
                    <div id="output-fill-area" />
                    <div class="form-text text-muted">
                        Tag step outputs to indicate the final dataset(s) to be generated by running this workflow.
                    </div>
                </div>
            </div>
            <div id="right-content" class="right-content" />
        </div>
    </div>
</template>

<script>
import Tags from "components/Common/Tags";
import { Services } from "components/Workflow/services";
export default {
    name: "EditorPanel",
    components: {
        Tags
    },
    data() {
        return {};
    },
    props: {
        workflow: {
            type: Object,
            required: true
        }
    },
    created() {
        this.services = new Services();
    },
    methods: {
        onTags(item) {},
        onRename(name) {
            this.services.updateWorkflow(this.workflow.id, { name } );
        }
    }
};
</script>
