<template>
    <div id="right" class="unified-panel">
        <div class="unified-panel-header" unselectable="on">
            <div class="unified-panel-header-inner">
                <div class="panel-header-text">Details</div>
            </div>
        </div>
        <div class="unified-panel-body workflow-right" style="overflow: auto;">
            <div id="edit-attributes" class="metadataForm right-content">
                <div class="metadataFormTitle">Edit Workflow Attributes</div>
                <div class="metadataFormBody">
                <div id="workflow-name-area" class="form-row">
                    <label>Name:</label>
                    <span id="workflow-name" class="editable-text" title="Click to rename workflow">h.to_unicode( stored.name ) | h</span>
                </div>
                <div id="workflow-version-area" class="form-row">
                    <label>Version:</label>
                </div>
                <select id="workflow-version-switch">Select version</select>
                <div class="form-row">
                    <label>
                        Tags:
                    </label>
                        <div style="float: left; width: 225px; margin-right: 10px; border-style: inset; border-width: 1px; margin-left: 2px">
                            render_individual_tagging_element(user=trans.get_user())
                        </div>
                        <div class="toolParamHelp">Apply tags to make it easy to search for and find items with the same tag.</div>
                    </div>
                    <div id="workflow-annotation-area" class="form-row">
                        <label>Annotation / Notes:</label>
                        <div id="workflow-annotation" class="editable-text" title="Click to edit annotation">
                        annotation
                        </div>
                        <div class="toolParamHelp">Add an annotation or notes to a workflow; annotations are available when a workflow is viewed.</div>
                    </div>
                </div>
            </div>
            <div id="right-content" class="right-content"></div>
            <div style="display:none;" id="workflow-output-area" class="metadataForm right-content">
                <div class="metadataFormTitle">Edit Workflow Outputs</div>
                <div class="metadataFormBody">
                    <div class="form-row">
                        <div class="toolParamHelp">Tag step outputs to indicate the final dataset(s) to be generated by running this workflow.</div>
                        <div id="output-fill-area"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "EditorPanel",
    data() {
        return {
        };
    },
    props: {
    },
    created() {
    },
    computed: {
    },
    methods: {
    }
};
</script>
