[pytest]
# Prevent execution of alembic/env.py at test collection stage (alembic.context not set).
# Also ignore functional tests (galaxy_test/ and tool_shed/test/).
addopts = --doctest-modules --ignore=src/galaxy/model/migrations/alembic/ --ignore=src/galaxy/tools/bundled/ --ignore=src/galaxy_test/ --ignore=src/tool_shed/test/ --ignore=src/tool_shed/webapp/model/migrations/alembic/ --doctest-continue-on-failure --verbosity=1
asyncio_mode = auto
log_level = DEBUG
consider_namespace_packages = true
pythonpath = src
