name: Check test class names
on:
  pull_request:
    paths:
      - '.ci/check_test_class_names.sh'
      - .github/workflows/check_test_class_names.yaml
      - 'lib/galaxy_test/**'
      - 'test/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          uv venv .venv
          . .venv/bin/activate
          uv pip install -r requirements.txt -r lib/galaxy/dependencies/pinned-test-requirements.txt
      - name: Run tests
        run: |
          . .venv/bin/activate
          .ci/check_test_class_names.sh
