name: Workflow framework tests
on:
  push:
    paths-ignore:
      - 'client/**'
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
      - 'packages/**'
  pull_request:
    paths-ignore:
      - 'client/**'
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
      - 'packages/**'
  schedule:
    # Run at midnight UTC every Tuesday
    - cron: '0 0 * * 2'
env:
  GALAXY_TEST_DBURI: 'postgresql://postgres:postgres@localhost:5432/galaxy?client_encoding=utf8'
  GALAXY_TEST_RAISE_EXCEPTION_ON_HISTORYLESS_HDA: '1'
  GALAXY_TEST_WORKFLOW_AFTER_RERUN: '1'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - if: github.event_name == 'schedule'
        run: |
          echo "GALAXY_CONFIG_OVERRIDE_METADATA_STRATEGY=extended" >> $GITHUB_ENV
          echo "GALAXY_CONFIG_OVERRIDE_OUTPUTS_TO_WORKING_DIRECTORY=true" >> $GITHUB_ENV
      - uses: actions/checkout@v5
        with:
          path: 'galaxy root'
          persist-credentials: false
      - name: Read Node.js version
        id: node-version
        run: echo "version=$(cat 'galaxy root/client/.node_version')" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: 'yarn'
          cache-dependency-path: 'galaxy root/client/yarn.lock'
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'galaxy root/requirements.txt'
      - name: Get full Python version
        id: full-python-version
        shell: bash
        run: echo "version=$(python -c 'import sys; print("-".join(str(v) for v in sys.version_info))')" >> $GITHUB_OUTPUT
      - name: Cache galaxy venv
        uses: actions/cache@v4
        with:
          path: 'galaxy root/.venv'
          key: gxy-venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('galaxy root/requirements.txt') }}-framework
      - name: Run tests
        run: ./run_tests.sh --coverage --framework-workflows
        working-directory: 'galaxy root'
      - uses: codecov/codecov-action@v5
        with:
          flags: framework-workflows
          working-directory: 'galaxy root'
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Workflow framework test results (${{ matrix.python-version }})
          path: 'galaxy root/run_framework_workflows_tests.html'
