name: Labels Verifier
on:
  pull_request_target:
    types: [closed]
jobs:
  onMerged:
    name: "Check Labels on merge"
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels on merge
        if: |
          github.event.pull_request.merged == true &&
          ! contains(join(github.event.pull_request.labels.*.name, ', '), 'kind/') &&
          ! contains(github.event.pull_request.labels.*.name, 'merge') &&
          ! contains(github.event.pull_request.labels.*.name, 'minor')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'This PR was merged without a "kind/" label, please correct.',
            })
