name: Python linting
on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/lint.yaml'
      - .flake8
      - .isort.cfg
      - lib/galaxy/dependencies/**
      - mypy.ini
      - pyproject.toml
      - tox.ini
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/lint.yaml'
      - .flake8
      - .isort.cfg
      - lib/galaxy/dependencies/**
      - mypy.ini
      - pyproject.toml
      - tox.ini
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  test:
    if: >-
      github.event_name != 'push'
      || github.repository_owner != 'galaxyproject'
      || github.ref_name == 'dev'
      || startsWith(github.ref_name, 'release_')
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
    env:
      LINT_PATH: 'lib/galaxy/dependencies/pinned-lint-requirements.txt'
      TYPE_PATH: 'lib/galaxy/dependencies/pinned-typecheck-requirements.txt'
      CORE_PATH: 'lib/galaxy/dependencies/pinned-requirements.txt'
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v8.3.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Run linting
        run: tox -e lint,lint_docstring_include_list,mypy,format
