name: Prune Ruff annotation exemption list
on:
  schedule:
    - cron: '0 4 * * 1'  # Run every monday at 4 am.
  workflow_dispatch:
permissions: {}
jobs:
  prune_exemption_list:
    name: Remove stale Ruff annotation exemption entries
    if: github.repository_owner == 'galaxyproject'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Remove stale entries
        run: tox -e ruff_exemptions -- --fix --summary "$RUNNER_TEMP/summary.md"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          author: galaxybot <galaxybot@users.noreply.github.com>
          token: ${{ secrets.GALAXYBOT_PAT }}
          add-paths: ruff.toml
          commit-message: |
            Remove stale Ruff annotation exemption entries

            by running `tox -e ruff_exemptions -- --fix`.
          branch: dev_auto_prune_ruff_exemption_list
          delete-branch: true
          push-to-fork: galaxybot/galaxy
          title: Remove stale Ruff annotation exemption entries
          body-path: ${{ runner.temp }}/summary.md
          labels: |
            area/testing
            kind/refactoring
