name: Tool Shed frontend
on:
  push:
    paths:
      - 'lib/tool_shed/webapp/frontend/**'
      - '.github/workflows/toolshed_frontend.yaml'
  pull_request:
    paths:
      - 'lib/tool_shed/webapp/frontend/**'
      - '.github/workflows/toolshed_frontend.yaml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  frontend:
    if: >-
      github.event_name != 'push'
      || github.repository_owner != 'galaxyproject'
      || github.ref_name == 'dev'
      || startsWith(github.ref_name, 'release_')
    name: Lint and unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/tool_shed/webapp/frontend
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Read Node.js version
        id: node-version
        run: echo "version=$(cat '.node_version')" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: lib/tool_shed/webapp/frontend/package.json
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run vue-tsc
        run: pnpm typecheck
      - name: Run ESLint
        run: pnpm lint
      - name: Run Vitest unit tests
        run: pnpm test:run
