import sys
import os


# Check if the given output file is ready for processing, exit with error code 1 if not.
def exit_if_output_not_ready(output):
    # Since Galaxy creates all output files with size 0 upon starting a job, we can't use the existence of output file 
    # to decide if the output has been created; rather, we can use its file size as the criteria.
    # If output hasn't been generated by the HMGM editor, exit with error code 1, 
    # so the HMGM job runner can requeue the step, and process will continue to wait for jira to be completed
    if not os.path.exists(output) or os.stat(output).st_size == 0:
        exit(1)
